// WARNING: THIS FILE IS GENERATED BY openusd-build. DO NOT EDIT.
// Generated from plugInfo.json.

/// The strings this library names things by.
///
/// A token's value is what a stage actually reads; the constant is a
/// name for it, so an application can say what it means instead of
/// retyping a string.
pub mod tokens {}

/// The library's name, which is the family its declarations register
/// under.
pub const LIBRARY_NAME: &str = "tinyKinds";

/// What this library declares, ready to register: its schemas, and
/// the metadata fields and kinds declared beside them.
///
/// Hand it to
/// [`SchemaRegistryBuilder::register`](::openusd::usd::SchemaRegistryBuilder::register):
/// a stage opened with the resulting registry resolves the fallbacks
/// of the schemas and metadata fields declared here, answers `is_a`
/// along the schemas' inheritance, and counts a declared kind as its
/// base kind. One opened without it knows none of them, so the typed
/// constructors answer `None`.
pub const SCHEMAS: &::openusd::usd::SchemaFamily<'static> = &::openusd::usd::SchemaFamily::new(
        LIBRARY_NAME,
        &[],
    )
    .kinds(
        &[
            ::openusd::kind::Decl::new("tinyCrowd").base("assembly"),
            ::openusd::kind::Decl::new("tinyMarker"),
            ::openusd::kind::Decl::new("tinyProp").base("component"),
        ],
    );
