// WARNING: THIS FILE IS GENERATED BY openusd-build. DO NOT EDIT.
// Generated from schema.usda.

/// The strings these schemas name things by.
///
/// A token's value is what a stage actually reads; the constant is a
/// name for it, so an application can say what it means instead of
/// retyping a string.
pub mod tokens {
    /// `"apiSchemas"`: A listop metadata containing the API schemas which have been
    /// applied to this prim, using the `Apply()` method on the particular schema
    /// class..
    pub const API_SCHEMAS: &str = "apiSchemas";
    /// `"automatic"`: the fallback of `CollectionAPI.mode`.
    pub const AUTOMATIC: &str = "automatic";
    /// `"clips"`: Dictionary that contains the definition of the clip sets on this
    /// prim. See `UsdClipsAPI::GetClips`..
    pub const CLIPS: &str = "clips";
    /// `"clipSets"`: `ListOp` that may be used to affect how opinions from clip
    /// sets are applied during value resolution. See `UsdClipsAPI::GetClipSets`..
    pub const CLIP_SETS: &str = "clipSets";
    /// `"collection"`: the property namespace prefix of `CollectionAPI`.
    pub const COLLECTION: &str = "collection";
    /// `"collection:__INSTANCE_NAME__"`: `CollectionAPI`.
    pub const COLLECTION_MULTIPLE_APPLY_TEMPLATE_: &str = "collection:__INSTANCE_NAME__";
    /// `"collection:__INSTANCE_NAME__:excludes"`: `CollectionAPI`.
    pub const COLLECTION_MULTIPLE_APPLY_TEMPLATE_EXCLUDES: &str = "collection:__INSTANCE_NAME__:excludes";
    /// `"collection:__INSTANCE_NAME__:expansionRule"`: `CollectionAPI`.
    pub const COLLECTION_MULTIPLE_APPLY_TEMPLATE_EXPANSION_RULE: &str = "collection:__INSTANCE_NAME__:expansionRule";
    /// `"collection:__INSTANCE_NAME__:includeRoot"`: `CollectionAPI`.
    pub const COLLECTION_MULTIPLE_APPLY_TEMPLATE_INCLUDE_ROOT: &str = "collection:__INSTANCE_NAME__:includeRoot";
    /// `"collection:__INSTANCE_NAME__:includes"`: `CollectionAPI`.
    pub const COLLECTION_MULTIPLE_APPLY_TEMPLATE_INCLUDES: &str = "collection:__INSTANCE_NAME__:includes";
    /// `"collection:__INSTANCE_NAME__:membershipExpression"`: `CollectionAPI`.
    pub const COLLECTION_MULTIPLE_APPLY_TEMPLATE_MEMBERSHIP_EXPRESSION: &str = "collection:__INSTANCE_NAME__:membershipExpression";
    /// `"collection:__INSTANCE_NAME__:mode"`: `CollectionAPI`.
    pub const COLLECTION_MULTIPLE_APPLY_TEMPLATE_MODE: &str = "collection:__INSTANCE_NAME__:mode";
    /// `"colorSpaceDefinition"`: the property namespace prefix of
    /// `ColorSpaceDefinitionAPI`.
    pub const COLOR_SPACE_DEFINITION: &str = "colorSpaceDefinition";
    /// `"colorSpaceDefinition:__INSTANCE_NAME__:blueChroma"`:
    /// `ColorSpaceDefinitionAPI`.
    pub const COLOR_SPACE_DEFINITION_MULTIPLE_APPLY_TEMPLATE_BLUE_CHROMA: &str = "colorSpaceDefinition:__INSTANCE_NAME__:blueChroma";
    /// `"colorSpaceDefinition:__INSTANCE_NAME__:gamma"`: `ColorSpaceDefinitionAPI`.
    pub const COLOR_SPACE_DEFINITION_MULTIPLE_APPLY_TEMPLATE_GAMMA: &str = "colorSpaceDefinition:__INSTANCE_NAME__:gamma";
    /// `"colorSpaceDefinition:__INSTANCE_NAME__:greenChroma"`:
    /// `ColorSpaceDefinitionAPI`.
    pub const COLOR_SPACE_DEFINITION_MULTIPLE_APPLY_TEMPLATE_GREEN_CHROMA: &str = "colorSpaceDefinition:__INSTANCE_NAME__:greenChroma";
    /// `"colorSpaceDefinition:__INSTANCE_NAME__:linearBias"`:
    /// `ColorSpaceDefinitionAPI`.
    pub const COLOR_SPACE_DEFINITION_MULTIPLE_APPLY_TEMPLATE_LINEAR_BIAS: &str = "colorSpaceDefinition:__INSTANCE_NAME__:linearBias";
    /// `"colorSpaceDefinition:__INSTANCE_NAME__:name"`: `ColorSpaceDefinitionAPI`.
    pub const COLOR_SPACE_DEFINITION_MULTIPLE_APPLY_TEMPLATE_NAME: &str = "colorSpaceDefinition:__INSTANCE_NAME__:name";
    /// `"colorSpaceDefinition:__INSTANCE_NAME__:redChroma"`:
    /// `ColorSpaceDefinitionAPI`.
    pub const COLOR_SPACE_DEFINITION_MULTIPLE_APPLY_TEMPLATE_RED_CHROMA: &str = "colorSpaceDefinition:__INSTANCE_NAME__:redChroma";
    /// `"colorSpaceDefinition:__INSTANCE_NAME__:whitePoint"`:
    /// `ColorSpaceDefinitionAPI`.
    pub const COLOR_SPACE_DEFINITION_MULTIPLE_APPLY_TEMPLATE_WHITE_POINT: &str = "colorSpaceDefinition:__INSTANCE_NAME__:whitePoint";
    /// `"colorSpace:name"`: `ColorSpaceAPI`.
    pub const COLOR_SPACE_NAME: &str = "colorSpace:name";
    /// `"custom"`: the fallback of `ColorSpaceDefinitionAPI.name`.
    pub const CUSTOM: &str = "custom";
    /// `"exclude"`: This is the token used to exclude a path from a collection.
    /// Although it is not a possible value for the "`expansionRule`" attribute, it
    /// is used as the `expansionRule` for excluded paths in
    /// `UsdCollectionAPI::MembershipQuery::IsPathIncluded`..
    pub const EXCLUDE: &str = "exclude";
    /// `"expandPrims"`: the fallback of `CollectionAPI.expansionRule`.
    pub const EXPAND_PRIMS: &str = "expandPrims";
    /// `"expandPrimsAndProperties"`: a value `CollectionAPI.expansionRule` admits.
    pub const EXPAND_PRIMS_AND_PROPERTIES: &str = "expandPrimsAndProperties";
    /// `"explicitOnly"`: a value `CollectionAPI.expansionRule` admits.
    pub const EXPLICIT_ONLY: &str = "explicitOnly";
    /// `"expression"`: a value `CollectionAPI.mode` admits.
    pub const EXPRESSION: &str = "expression";
    /// `"fallbackPrimTypes"`: A dictionary metadata that maps the name of a
    /// concrete schema prim type to an ordered list of schema prim types to use
    /// instead if the schema prim type doesn't exist in version of USD being used..
    pub const FALLBACK_PRIM_TYPES: &str = "fallbackPrimTypes";
    /// `"relationship"`: a value `CollectionAPI.mode` admits.
    pub const RELATIONSHIP: &str = "relationship";
    /// `"APISchemaBase"`: the schema identifier and family of `APISchemaBase`.
    pub const API_SCHEMA_BASE: &str = "APISchemaBase";
    /// `"ClipsAPI"`: the schema identifier and family of `ClipsAPI`.
    pub const CLIPS_API: &str = "ClipsAPI";
    /// `"CollectionAPI"`: the schema identifier and family of `CollectionAPI`.
    pub const COLLECTION_API: &str = "CollectionAPI";
    /// `"ColorSpaceAPI"`: the schema identifier and family of `ColorSpaceAPI`.
    pub const COLOR_SPACE_API: &str = "ColorSpaceAPI";
    /// `"ColorSpaceDefinitionAPI"`: the schema identifier and family of
    /// `ColorSpaceDefinitionAPI`.
    pub const COLOR_SPACE_DEFINITION_API: &str = "ColorSpaceDefinitionAPI";
    /// `"ModelAPI"`: the schema identifier and family of `ModelAPI`.
    pub const MODEL_API: &str = "ModelAPI";
    /// `"SchemaBase"`: the schema identifier and family of `SchemaBase`.
    pub const SCHEMA_BASE: &str = "SchemaBase";
    /// `"Typed"`: the schema identifier and family of `Typed`.
    pub const TYPED: &str = "Typed";
}

/// The library these schemas belong to, as their manifest records it.
pub const LIBRARY_NAME: &str = "usd";

/// The schemas this library declares, ready to register.
///
/// Hand it to
/// [`SchemaRegistryBuilder::register`](::openusd::usd::SchemaRegistryBuilder::register):
/// a stage opened with the resulting registry resolves these schemas'
/// fallbacks and answers `is_a` along their inheritance, and one opened
/// without it knows nothing about them, so the typed constructors
/// answer `None`.
pub const SCHEMAS: &::openusd::usd::SchemaFamily<'static> = &::openusd::usd::SchemaFamily::new(
    LIBRARY_NAME,
    &[
        ::openusd::usd::SchemaDecl::new(
            "SchemaBase",
            ::openusd::usd::SchemaKind::AbstractBase,
        ),
        ::openusd::usd::SchemaDecl::new(
                "Typed",
                ::openusd::usd::SchemaKind::AbstractBase,
            )
            .bases(&["SchemaBase"]),
        ::openusd::usd::SchemaDecl::new(
                "APISchemaBase",
                ::openusd::usd::SchemaKind::AbstractBase,
            )
            .bases(&["SchemaBase"]),
        ::openusd::usd::SchemaDecl::new(
                "ModelAPI",
                ::openusd::usd::SchemaKind::NonAppliedApi,
            )
            .bases(&["APISchemaBase"]),
        ::openusd::usd::SchemaDecl::new(
                "ColorSpaceAPI",
                ::openusd::usd::SchemaKind::SingleApplyApi,
            )
            .bases(&["APISchemaBase"])
            .properties(
                &[
                    ::openusd::usd::PropertyDecl::attribute("colorSpace:name", "token")
                        .uniform(),
                ],
            ),
        ::openusd::usd::SchemaDecl::new(
                "ColorSpaceDefinitionAPI",
                ::openusd::usd::SchemaKind::MultipleApplyApi,
            )
            .bases(&["APISchemaBase"])
            .property_namespace_prefix("colorSpaceDefinition")
            .properties(
                &[
                    ::openusd::usd::PropertyDecl::attribute(
                            "colorSpaceDefinition:__INSTANCE_NAME__:name",
                            "token",
                        )
                        .uniform()
                        .fields(&[::openusd::usd::Field::token("default", "custom")]),
                    ::openusd::usd::PropertyDecl::attribute(
                            "colorSpaceDefinition:__INSTANCE_NAME__:redChroma",
                            "float2",
                        )
                        .varying()
                        .fields(
                            &[
                                ::openusd::usd::Field::new(
                                    "default",
                                    || ::openusd::sdf::Value::Vec2f(
                                        ::openusd::gf::vec2f(1f32, 0f32),
                                    ),
                                ),
                            ],
                        ),
                    ::openusd::usd::PropertyDecl::attribute(
                            "colorSpaceDefinition:__INSTANCE_NAME__:greenChroma",
                            "float2",
                        )
                        .varying()
                        .fields(
                            &[
                                ::openusd::usd::Field::new(
                                    "default",
                                    || ::openusd::sdf::Value::Vec2f(
                                        ::openusd::gf::vec2f(0f32, 1f32),
                                    ),
                                ),
                            ],
                        ),
                    ::openusd::usd::PropertyDecl::attribute(
                            "colorSpaceDefinition:__INSTANCE_NAME__:blueChroma",
                            "float2",
                        )
                        .varying()
                        .fields(
                            &[
                                ::openusd::usd::Field::new(
                                    "default",
                                    || ::openusd::sdf::Value::Vec2f(
                                        ::openusd::gf::vec2f(0f32, 0f32),
                                    ),
                                ),
                            ],
                        ),
                    ::openusd::usd::PropertyDecl::attribute(
                            "colorSpaceDefinition:__INSTANCE_NAME__:whitePoint",
                            "float2",
                        )
                        .varying()
                        .fields(
                            &[
                                ::openusd::usd::Field::new(
                                    "default",
                                    || ::openusd::sdf::Value::Vec2f(
                                        ::openusd::gf::vec2f(0.33333334f32, 0.33333334f32),
                                    ),
                                ),
                            ],
                        ),
                    ::openusd::usd::PropertyDecl::attribute(
                            "colorSpaceDefinition:__INSTANCE_NAME__:gamma",
                            "float",
                        )
                        .varying()
                        .fields(
                            &[
                                ::openusd::usd::Field::new(
                                    "default",
                                    || ::openusd::sdf::Value::Float(1f32),
                                ),
                            ],
                        ),
                    ::openusd::usd::PropertyDecl::attribute(
                            "colorSpaceDefinition:__INSTANCE_NAME__:linearBias",
                            "float",
                        )
                        .varying()
                        .fields(
                            &[
                                ::openusd::usd::Field::new(
                                    "default",
                                    || ::openusd::sdf::Value::Float(0f32),
                                ),
                            ],
                        ),
                ],
            ),
        ::openusd::usd::SchemaDecl::new(
                "CollectionAPI",
                ::openusd::usd::SchemaKind::MultipleApplyApi,
            )
            .bases(&["APISchemaBase"])
            .property_namespace_prefix("collection")
            .properties(
                &[
                    ::openusd::usd::PropertyDecl::attribute(
                            "collection:__INSTANCE_NAME__:expansionRule",
                            "token",
                        )
                        .uniform()
                        .fields(
                            &[
                                ::openusd::usd::Field::strings(
                                    "allowedTokens",
                                    &["explicitOnly", "expandPrims", "expandPrimsAndProperties"],
                                ),
                                ::openusd::usd::Field::token("default", "expandPrims"),
                            ],
                        ),
                    ::openusd::usd::PropertyDecl::attribute(
                            "collection:__INSTANCE_NAME__:includeRoot",
                            "bool",
                        )
                        .uniform(),
                    ::openusd::usd::PropertyDecl::relationship(
                            "collection:__INSTANCE_NAME__:includes",
                        )
                        .uniform(),
                    ::openusd::usd::PropertyDecl::relationship(
                            "collection:__INSTANCE_NAME__:excludes",
                        )
                        .uniform(),
                    ::openusd::usd::PropertyDecl::attribute(
                            "collection:__INSTANCE_NAME__:membershipExpression",
                            "pathExpression",
                        )
                        .uniform(),
                    ::openusd::usd::PropertyDecl::attribute(
                            "collection:__INSTANCE_NAME__:mode",
                            "token",
                        )
                        .uniform()
                        .fields(
                            &[
                                ::openusd::usd::Field::strings(
                                    "allowedTokens",
                                    &["automatic", "relationship", "expression"],
                                ),
                                ::openusd::usd::Field::token("default", "automatic"),
                            ],
                        ),
                    ::openusd::usd::PropertyDecl::attribute(
                            "collection:__INSTANCE_NAME__",
                            "opaque",
                        )
                        .uniform(),
                ],
            ),
        ::openusd::usd::SchemaDecl::new(
                "ClipsAPI",
                ::openusd::usd::SchemaKind::NonAppliedApi,
            )
            .bases(&["APISchemaBase"]),
    ],
);
