// WARNING: THIS FILE IS GENERATED BY openusd-build. DO NOT EDIT.
// Generated from schema.usda.

/// The strings these schemas name things by.
///
/// A token's value is what a stage actually reads; the constant is a
/// name for it, so an application can say what it means instead of
/// retyping a string.
pub mod tokens {
    /// `"bounds"`: a value `Shape.drawMode` admits.
    pub const BOUNDS: &str = "bounds";
    /// `"default"`: the fallback of `Shape.drawMode`.
    pub const DEFAULT_: &str = "default";
    /// `"density"`: `Shape`, `Ball`.
    pub const DENSITY: &str = "density";
    /// `"drawMode"`: `Shape`, `Ball`.
    pub const DRAW_MODE: &str = "drawMode";
    /// `"extent"`: `Shape`, `Ball`.
    pub const EXTENT: &str = "extent";
    /// `"material"`: `Ball`.
    pub const MATERIAL: &str = "material";
    /// `"radius"`: `Ball`.
    pub const RADIUS: &str = "radius";
    /// `"!sentinel!"`: a value this library gives no property.
    pub const SENTINEL: &str = "!sentinel!";
    /// `"shapeKind"`: how a shape is classified.
    pub const SHAPE_KIND: &str = "shapeKind";
    /// `"slot"`: the property namespace prefix of `SlotAPI`.
    pub const SLOT: &str = "slot";
    /// `"slot:__INSTANCE_NAME__"`: `SlotAPI`.
    pub const SLOT_MULTIPLE_APPLY_TEMPLATE_: &str = "slot:__INSTANCE_NAME__";
    /// `"slot:__INSTANCE_NAME__:depth"`: `SlotAPI`.
    pub const SLOT_MULTIPLE_APPLY_TEMPLATE_DEPTH: &str = "slot:__INSTANCE_NAME__:depth";
    /// `"slot:__INSTANCE_NAME__:offset"`: `SlotAPI`.
    pub const SLOT_MULTIPLE_APPLY_TEMPLATE_OFFSET: &str = "slot:__INSTANCE_NAME__:offset";
    /// `"tag"`: `TagAPI`.
    pub const TAG: &str = "tag";
    /// `"temperature"`: `Ball`.
    pub const TEMPERATURE: &str = "temperature";
    /// `"Ball"`: the schema identifier and family of `Ball`.
    pub const BALL: &str = "Ball";
    /// `"Shape"`: the schema identifier and family of `Shape`.
    pub const SHAPE: &str = "Shape";
    /// `"SlotAPI"`: the schema identifier and family of `SlotAPI`.
    pub const SLOT_API: &str = "SlotAPI";
    /// `"TagAPI"`: the schema identifier and family of `TagAPI`.
    pub const TAG_API: &str = "TagAPI";
}

/// The library these schemas belong to, as their manifest records it.
pub const LIBRARY_NAME: &str = "tiny";

/// The schemas this library declares, ready to register.
///
/// Hand it to
/// [`SchemaRegistryBuilder::register`](::openusd::usd::SchemaRegistryBuilder::register):
/// a stage opened with the resulting registry resolves these schemas'
/// fallbacks and answers `is_a` along their inheritance, and one opened
/// without it knows nothing about them, so the typed constructors
/// answer `None`.
pub const SCHEMAS: &::openusd::usd::SchemaFamily<'static> = &::openusd::usd::SchemaFamily::new(
    LIBRARY_NAME,
    &[
        ::openusd::usd::SchemaDecl::new(
                "Shape",
                ::openusd::usd::SchemaKind::AbstractTyped,
            )
            .bases(&["Typed"])
            .properties(
                &[
                    ::openusd::usd::PropertyDecl::attribute("extent", "double3")
                        .varying()
                        .fields(
                            &[
                                ::openusd::usd::Field::new(
                                    "default",
                                    || ::openusd::sdf::Value::Vec3d(
                                        ::openusd::gf::vec3d(1f64, 1f64, 1f64),
                                    ),
                                ),
                            ],
                        ),
                    ::openusd::usd::PropertyDecl::attribute("drawMode", "token")
                        .uniform()
                        .fields(
                            &[
                                ::openusd::usd::Field::strings(
                                    "allowedTokens",
                                    &["default", "bounds"],
                                ),
                                ::openusd::usd::Field::token("default", "default"),
                            ],
                        ),
                    ::openusd::usd::PropertyDecl::attribute("density", "double")
                        .varying()
                        .fields(
                            &[
                                ::openusd::usd::Field::new(
                                    "default",
                                    || ::openusd::sdf::Value::Double(1f64),
                                ),
                            ],
                        ),
                ],
            ),
        ::openusd::usd::SchemaDecl::new(
                "Ball",
                ::openusd::usd::SchemaKind::ConcreteTyped,
            )
            .bases(&["Shape"])
            .properties(
                &[
                    ::openusd::usd::PropertyDecl::attribute("extent", "double3")
                        .varying()
                        .fields(
                            &[
                                ::openusd::usd::Field::new(
                                    "default",
                                    || ::openusd::sdf::Value::Vec3d(
                                        ::openusd::gf::vec3d(2f64, 2f64, 2f64),
                                    ),
                                ),
                            ],
                        ),
                    ::openusd::usd::PropertyDecl::attribute("drawMode", "token")
                        .uniform()
                        .fields(
                            &[
                                ::openusd::usd::Field::strings(
                                    "allowedTokens",
                                    &["default", "bounds"],
                                ),
                                ::openusd::usd::Field::token("default", "default"),
                            ],
                        ),
                    ::openusd::usd::PropertyDecl::attribute("density", "double")
                        .varying()
                        .fields(
                            &[
                                ::openusd::usd::Field::new(
                                    "default",
                                    || ::openusd::sdf::Value::Double(1f64),
                                ),
                            ],
                        ),
                    ::openusd::usd::PropertyDecl::attribute("radius", "double")
                        .varying()
                        .fields(
                            &[
                                ::openusd::usd::Field::new(
                                    "default",
                                    || ::openusd::sdf::Value::Double(1f64),
                                ),
                            ],
                        ),
                    ::openusd::usd::PropertyDecl::attribute("temperature", "float")
                        .varying()
                        .custom(),
                    ::openusd::usd::PropertyDecl::relationship("material").uniform(),
                ],
            ),
        ::openusd::usd::SchemaDecl::new(
                "TagAPI",
                ::openusd::usd::SchemaKind::SingleApplyApi,
            )
            .bases(&["APISchemaBase"])
            .can_only_apply_to(&["Ball"])
            .properties(
                &[
                    ::openusd::usd::PropertyDecl::attribute("tag", "string")
                        .varying()
                        .fields(&[::openusd::usd::Field::string("default", "")]),
                ],
            ),
        ::openusd::usd::SchemaDecl::new(
                "SlotAPI",
                ::openusd::usd::SchemaKind::MultipleApplyApi,
            )
            .bases(&["APISchemaBase"])
            .property_namespace_prefix("slot")
            .instance_restrictions(&[("front", &["Ball"])])
            .allowed_instance_names(&["front", "back"])
            .properties(
                &[
                    ::openusd::usd::PropertyDecl::attribute(
                            "slot:__INSTANCE_NAME__",
                            "opaque",
                        )
                        .varying(),
                    ::openusd::usd::PropertyDecl::attribute(
                            "slot:__INSTANCE_NAME__:depth",
                            "int",
                        )
                        .varying()
                        .fields(
                            &[
                                ::openusd::usd::Field::new(
                                    "default",
                                    || ::openusd::sdf::Value::Int(0i32),
                                ),
                            ],
                        ),
                    ::openusd::usd::PropertyDecl::attribute(
                            "slot:__INSTANCE_NAME__:offset",
                            "double3",
                        )
                        .varying()
                        .fields(
                            &[
                                ::openusd::usd::Field::new(
                                    "default",
                                    || ::openusd::sdf::Value::Vec3d(
                                        ::openusd::gf::vec3d(0f64, 0f64, 0f64),
                                    ),
                                ),
                            ],
                        ),
                ],
            ),
    ],
);

/// Something with an extent, which everything drawable has.
///
/// The accessors [`Shape`] carries. They live on a trait so that a schema
/// deriving from this one carries them too.
pub trait ShapeSchema: ::openusd::usd::Typed {
    /// The bounds, in the shape's own space.
    ///
    /// Declared `double3 extent = (1.0, 1.0, 1.0)`. Read it with
    /// `get::<::openusd::gf::Vec3d>()`.
    fn extent_attr(&self) -> ::openusd::usd::Attribute {
        self.prim().attribute(tokens::EXTENT)
    }
    /// The property's declaration, unauthored. Give it a value and
    /// `build` it to author both as one edit; `build` it alone for the
    /// declaration by itself.
    fn extent_attr_builder(&self) -> ::openusd::usd::AttributeBuilder<'static> {
        self.prim()
            .attribute_builder(tokens::EXTENT, ::openusd::sdf::ValueTypeName::DOUBLE3)
            .custom(false)
    }
    /// Authors the property as the schema declares it, and returns it.
    fn create_extent_attr(&self) -> ::openusd::Result<::openusd::usd::Attribute> {
        ::std::result::Result::Ok(self.extent_attr_builder().build()?)
    }
    /// How the shape draws.
    ///
    /// Declared `uniform token drawMode = "default"`. One of `default`, `bounds`.
    /// Read it with `get::<::openusd::tf::Token>()`.
    fn draw_mode_attr(&self) -> ::openusd::usd::Attribute {
        self.prim().attribute(tokens::DRAW_MODE)
    }
    /// The property's declaration, unauthored. Give it a value and
    /// `build` it to author both as one edit; `build` it alone for the
    /// declaration by itself.
    fn draw_mode_attr_builder(&self) -> ::openusd::usd::AttributeBuilder<'static> {
        self.prim()
            .attribute_builder(tokens::DRAW_MODE, ::openusd::sdf::ValueTypeName::TOKEN)
            .custom(false)
            .variability(::openusd::sdf::Variability::Uniform)
    }
    /// Authors the property as the schema declares it, and returns it.
    fn create_draw_mode_attr(&self) -> ::openusd::Result<::openusd::usd::Attribute> {
        ::std::result::Result::Ok(self.draw_mode_attr_builder().build()?)
    }
    /// The property's declaration, unauthored. Give it a value and
    /// `build` it to author both as one edit; `build` it alone for the
    /// declaration by itself.
    fn density_attr_builder(&self) -> ::openusd::usd::AttributeBuilder<'static> {
        self.prim()
            .attribute_builder(tokens::DENSITY, ::openusd::sdf::ValueTypeName::DOUBLE)
            .custom(false)
    }
    /// Authors the property as the schema declares it, and returns it.
    fn create_density_attr(&self) -> ::openusd::Result<::openusd::usd::Attribute> {
        ::std::result::Result::Ok(self.density_attr_builder().build()?)
    }
}

/// Something with an extent, which everything drawable has.
///
/// # Accessors
///
/// Its accessors live on [`ShapeSchema`], which a caller has to have in scope
/// to reach one.
#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct Shape(::openusd::usd::Prim);

impl Shape {
    /// Views `prim` as this schema without asking whether it is one.
    ///
    /// Unchecked of the schema, not of memory: nothing here is
    /// `unsafe`, and a prim of another type simply answers nothing
    /// for the properties this schema declares.
    /// [`from_prim`](Self::from_prim) is the constructor that asks.
    pub fn from_prim_unchecked(prim: ::openusd::usd::Prim) -> Self {
        Self(prim)
    }
    /// Views `prim` as this schema, or `None` where it is not one.
    ///
    /// The stage's registry is what answers, so a prim from a stage
    /// opened without this library's family registered is never one.
    pub fn from_prim(
        prim: ::openusd::usd::Prim,
    ) -> ::openusd::Result<::std::option::Option<Self>> {
        ::std::result::Result::Ok(prim.is_a(tokens::SHAPE)?.then_some(Self(prim)))
    }
    /// Views the prim at `path` as this schema, or `None` where it
    /// is not one — [`from_prim`](Self::from_prim) over the prim
    /// `path` names.
    pub fn get(
        stage: &::openusd::usd::Stage,
        path: impl ::openusd::sdf::IntoPath,
    ) -> ::openusd::Result<::std::option::Option<Self>> {
        Self::from_prim(stage.prim(path)?)
    }
}

impl ::openusd::usd::SchemaBase for Shape {
    const KIND: ::openusd::usd::SchemaKind = ::openusd::usd::SchemaKind::AbstractTyped;
    fn prim(&self) -> &::openusd::usd::Prim {
        &self.0
    }
}

impl ::std::ops::Deref for Shape {
    type Target = ::openusd::usd::Prim;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl ShapeSchema for Shape {}

impl ::openusd::usd::Typed for Shape {}

/// A sphere, by another name. A [`Ball`] is a [`Shape`], so it has an
/// extent as well as a radius.
/// See also [`radius_attr`](BallSchema::radius_attr)
/// See also [`extent_attr`](ShapeSchema::extent_attr)
/// See also `ComputeSomethingOnlyCppHas()`
///
/// The accessors [`Ball`] carries. They live on a trait so that a schema
/// deriving from this one carries them too.
pub trait BallSchema: ShapeSchema {
    /// The radius.
    ///
    /// Declared `double radius = 1.0`. Read it with `get::<f64>()`.
    fn radius_attr(&self) -> ::openusd::usd::Attribute {
        self.prim().attribute(tokens::RADIUS)
    }
    /// The property's declaration, unauthored. Give it a value and
    /// `build` it to author both as one edit; `build` it alone for the
    /// declaration by itself.
    fn radius_attr_builder(&self) -> ::openusd::usd::AttributeBuilder<'static> {
        self.prim()
            .attribute_builder(tokens::RADIUS, ::openusd::sdf::ValueTypeName::DOUBLE)
            .custom(false)
    }
    /// Authors the property as the schema declares it, and returns it.
    fn create_radius_attr(&self) -> ::openusd::Result<::openusd::usd::Attribute> {
        ::std::result::Result::Ok(self.radius_attr_builder().build()?)
    }
    /// How warm it is, which no schema owns.
    ///
    /// Declared `custom float temperature`. Read it with `get::<f32>()`.
    fn temperature_attr(&self) -> ::openusd::usd::Attribute {
        self.prim().attribute(tokens::TEMPERATURE)
    }
    /// The property's declaration, unauthored. Give it a value and
    /// `build` it to author both as one edit; `build` it alone for the
    /// declaration by itself.
    fn temperature_attr_builder(&self) -> ::openusd::usd::AttributeBuilder<'static> {
        self.prim()
            .attribute_builder(tokens::TEMPERATURE, ::openusd::sdf::ValueTypeName::FLOAT)
    }
    /// Authors the property as the schema declares it, and returns it.
    fn create_temperature_attr(&self) -> ::openusd::Result<::openusd::usd::Attribute> {
        ::std::result::Result::Ok(self.temperature_attr_builder().build()?)
    }
    /// What the ball is made of.
    ///
    /// Declared `rel material`.
    fn material_rel(&self) -> ::openusd::usd::Relationship {
        self.prim().relationship(tokens::MATERIAL)
    }
    /// The property's declaration, unauthored. Give it a value and
    /// `build` it to author both as one edit; `build` it alone for the
    /// declaration by itself.
    fn material_rel_builder(&self) -> ::openusd::usd::RelationshipBuilder<'static> {
        self.prim().relationship_builder(tokens::MATERIAL).custom(false)
    }
    /// Authors the property as the schema declares it, and returns it.
    fn create_material_rel(&self) -> ::openusd::Result<::openusd::usd::Relationship> {
        ::std::result::Result::Ok(self.material_rel_builder().build()?)
    }
}

/// A sphere, by another name. A [`Ball`] is a [`Shape`], so it has an
/// extent as well as a radius.
/// See also [`radius_attr`](BallSchema::radius_attr)
/// See also [`extent_attr`](ShapeSchema::extent_attr)
/// See also `ComputeSomethingOnlyCppHas()`
///
/// # Accessors
///
/// A property is reached through the trait that declares it, which a caller
/// has to have in scope. This schema's own are on [`BallSchema`]; the rest come
/// from the classes behind it, on [`ShapeSchema`].
#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct Ball(::openusd::usd::Prim);

impl Ball {
    /// Views `prim` as this schema without asking whether it is one.
    ///
    /// Unchecked of the schema, not of memory: nothing here is
    /// `unsafe`, and a prim of another type simply answers nothing
    /// for the properties this schema declares.
    /// [`from_prim`](Self::from_prim) is the constructor that asks.
    pub fn from_prim_unchecked(prim: ::openusd::usd::Prim) -> Self {
        Self(prim)
    }
    /// Defines a prim of this schema at `path` and views it.
    pub fn define(
        stage: &::openusd::usd::Stage,
        path: impl ::openusd::sdf::IntoPath,
    ) -> ::openusd::Result<Self> {
        ::std::result::Result::Ok(Self(stage.define_typed_prim(path, tokens::BALL)?))
    }
    /// Views `prim` as this schema, or `None` where it is not one.
    ///
    /// The stage's registry is what answers, so a prim from a stage
    /// opened without this library's family registered is never one.
    pub fn from_prim(
        prim: ::openusd::usd::Prim,
    ) -> ::openusd::Result<::std::option::Option<Self>> {
        ::std::result::Result::Ok(prim.is_a(tokens::BALL)?.then_some(Self(prim)))
    }
    /// Views the prim at `path` as this schema, or `None` where it
    /// is not one — [`from_prim`](Self::from_prim) over the prim
    /// `path` names.
    pub fn get(
        stage: &::openusd::usd::Stage,
        path: impl ::openusd::sdf::IntoPath,
    ) -> ::openusd::Result<::std::option::Option<Self>> {
        Self::from_prim(stage.prim(path)?)
    }
}

impl ::openusd::usd::SchemaBase for Ball {
    const KIND: ::openusd::usd::SchemaKind = ::openusd::usd::SchemaKind::ConcreteTyped;
    fn prim(&self) -> &::openusd::usd::Prim {
        &self.0
    }
}

impl ::std::ops::Deref for Ball {
    type Target = ::openusd::usd::Prim;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl BallSchema for Ball {}

impl ::openusd::usd::Typed for Ball {}

impl ShapeSchema for Ball {}

/// Names a prim for a pipeline to find later.
#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct TagAPI(::openusd::usd::Prim);

impl TagAPI {
    /// Views `prim` as this schema whether or not it carries it.
    ///
    /// Unchecked of the schema, not of memory: nothing here is
    /// `unsafe`, and a prim that does not carry this schema simply
    /// answers nothing for the properties it declares.
    /// [`from_prim`](Self::from_prim) is the constructor that asks.
    pub fn from_prim_unchecked(prim: ::openusd::usd::Prim) -> Self {
        Self(prim)
    }
    /// Applies the schema to `prim` and views it.
    pub fn apply(prim: &::openusd::usd::Prim) -> ::openusd::Result<Self> {
        ::std::result::Result::Ok(Self(prim.clone().apply_api(tokens::TAG_API)?))
    }
    /// Whether the schema may be applied to `prim`.
    pub fn can_apply(
        prim: &::openusd::usd::Prim,
    ) -> ::std::result::Result<(), ::openusd::usd::ApplyApiError> {
        prim.can_apply_api(tokens::TAG_API)
    }
    /// Views `prim` as this schema, or `None` where it does not carry
    /// it.
    pub fn from_prim(
        prim: ::openusd::usd::Prim,
    ) -> ::openusd::Result<::std::option::Option<Self>> {
        ::std::result::Result::Ok(
            prim.has_api_schema(tokens::TAG_API)?.then_some(Self(prim)),
        )
    }
    /// Views the prim at `path` as this schema, or `None` where it does
    /// not carry it — [`from_prim`](Self::from_prim) over the prim
    /// `path` names.
    pub fn get(
        stage: &::openusd::usd::Stage,
        path: impl ::openusd::sdf::IntoPath,
    ) -> ::openusd::Result<::std::option::Option<Self>> {
        Self::from_prim(stage.prim(path)?)
    }
    /// The name the pipeline looks for.
    ///
    /// Declared `string tag = ""`. Read it with `get::<String>()`.
    pub fn tag_attr(&self) -> ::openusd::usd::Attribute {
        self.attribute(tokens::TAG)
    }
    /// The property's declaration, unauthored. Give it a value and
    /// `build` it to author both as one edit; `build` it alone for the
    /// declaration by itself.
    pub fn tag_attr_builder(&self) -> ::openusd::usd::AttributeBuilder<'static> {
        self.attribute_builder(tokens::TAG, ::openusd::sdf::ValueTypeName::STRING)
            .custom(false)
    }
    /// Authors the property as the schema declares it, and returns it.
    pub fn create_tag_attr(&self) -> ::openusd::Result<::openusd::usd::Attribute> {
        ::std::result::Result::Ok(self.tag_attr_builder().build()?)
    }
}

impl ::openusd::usd::SchemaBase for TagAPI {
    const KIND: ::openusd::usd::SchemaKind = ::openusd::usd::SchemaKind::SingleApplyApi;
    fn prim(&self) -> &::openusd::usd::Prim {
        &self.0
    }
}

impl ::std::ops::Deref for TagAPI {
    type Target = ::openusd::usd::Prim;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl ::openusd::usd::APISchemaBase for TagAPI {}

/// One of several interchangeable attachment points.
#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct SlotAPI {
    prim: ::openusd::usd::Prim,
    name: ::openusd::tf::Token,
}

impl SlotAPI {
    /// Views `prim` as this schema applied under `name`, whether or not
    /// it is.
    ///
    /// Unchecked of the schema, not of memory: nothing here is
    /// `unsafe`, and a prim that does not carry this schema under this
    /// name simply answers nothing for the properties it declares.
    /// [`get_instance`](Self::get_instance) is the constructor that
    /// asks.
    pub fn from_prim_unchecked(
        prim: ::openusd::usd::Prim,
        name: impl ::std::convert::Into<::openusd::tf::Token>,
    ) -> Self {
        Self { prim, name: name.into() }
    }
    /// The instance name this view reads its properties under.
    pub fn name(&self) -> &::openusd::tf::Token {
        &self.name
    }
    /// Applies the schema to `prim` under `name` and views it.
    pub fn apply(
        prim: &::openusd::usd::Prim,
        name: impl ::std::convert::Into<::openusd::tf::Token>,
    ) -> ::openusd::Result<Self> {
        let name = name.into();
        let applied = ::openusd::usd::SchemaRegistry::make_applied_name(
            tokens::SLOT_API,
            name.as_str(),
        );
        ::std::result::Result::Ok(Self {
            prim: prim.clone().apply_api(applied)?,
            name,
        })
    }
    /// Views `prim` as this schema applied under `name`, or `None`
    /// where it does not carry it.
    pub fn get_instance(
        prim: &::openusd::usd::Prim,
        name: impl ::std::convert::Into<::openusd::tf::Token>,
    ) -> ::openusd::Result<::std::option::Option<Self>> {
        let name = name.into();
        let applied = ::openusd::usd::SchemaRegistry::make_applied_name(
            tokens::SLOT_API,
            name.as_str(),
        );
        let carried = prim.has_api_schema(applied)?;
        ::std::result::Result::Ok(carried.then(|| Self { prim: prim.clone(), name }))
    }
    /// Whether the schema may be applied to `prim` under `name`.
    pub fn can_apply(
        prim: &::openusd::usd::Prim,
        name: &str,
    ) -> ::std::result::Result<(), ::openusd::usd::ApplyApiError> {
        prim.can_apply_api(
            ::openusd::usd::SchemaRegistry::make_applied_name(tokens::SLOT_API, name),
        )
    }
    /// Every instance of this schema applied to `prim`.
    pub fn get_all(
        prim: &::openusd::usd::Prim,
    ) -> ::openusd::Result<::std::vec::Vec<Self>> {
        let mut found = ::std::vec::Vec::new();
        for applied in prim.api_schemas()? {
            let (schema, instance) = ::openusd::usd::SchemaRegistry::type_name_and_instance(
                &applied,
            );
            let mine = instance.filter(|_| schema.as_str() == tokens::SLOT_API);
            if let ::std::option::Option::Some(name) = mine {
                found.push(Self { prim: prim.clone(), name });
            }
        }
        ::std::result::Result::Ok(found)
    }
    /// Whether `base_name` is one of the property names this schema
    /// declares, which an instance name may therefore not end with.
    pub fn is_schema_property_base_name(base_name: &str) -> bool {
        ::std::matches!(base_name, "" | "depth" | "offset")
    }
    /// The prim and instance name a property path of this schema names,
    /// or `None` where `path` names no instance of it.
    ///
    /// The identity property is what this recognises: a path reaching a
    /// property the schema declares belongs to an instance, but does not
    /// name one.
    pub fn instance_at_path(
        path: &::openusd::sdf::Path,
    ) -> ::std::option::Option<(::openusd::sdf::Path, ::openusd::tf::Token)> {
        let (prim, property) = path.split_property()?;
        if !property.split(':').all(::openusd::sdf::Path::is_valid_identifier) {
            return ::std::option::Option::None;
        }
        let instance = property.strip_prefix("slot")?.strip_prefix(':')?;
        let base_name = instance.rsplit(':').next()?;
        match Self::is_schema_property_base_name(base_name) {
            true => ::std::option::Option::None,
            false => {
                ::std::option::Option::Some((prim, ::openusd::tf::Token::from(instance)))
            }
        }
    }
    /// The slot itself, which carries no value.
    ///
    /// Declared `opaque slot:__INSTANCE_NAME__`.
    pub fn slot_attr(&self) -> ::openusd::usd::Attribute {
        self.attribute(
            ::openusd::usd::SchemaRegistry::make_multiple_apply_name_instance(
                tokens::SLOT_MULTIPLE_APPLY_TEMPLATE_,
                self.name.as_str(),
            ),
        )
    }
    /// The property's declaration, unauthored. Give it a value and
    /// `build` it to author both as one edit; `build` it alone for the
    /// declaration by itself.
    pub fn slot_attr_builder(&self) -> ::openusd::usd::AttributeBuilder<'static> {
        self.attribute_builder(
                ::openusd::usd::SchemaRegistry::make_multiple_apply_name_instance(
                    tokens::SLOT_MULTIPLE_APPLY_TEMPLATE_,
                    self.name.as_str(),
                ),
                ::openusd::sdf::ValueTypeName::OPAQUE,
            )
            .custom(false)
    }
    /// Authors the property as the schema declares it, and returns it.
    pub fn create_slot_attr(&self) -> ::openusd::Result<::openusd::usd::Attribute> {
        ::std::result::Result::Ok(self.slot_attr_builder().build()?)
    }
    /// How far in the slot sits.
    ///
    /// Declared `int slot:__INSTANCE_NAME__:depth = 0`. Read it with
    /// `get::<i32>()`.
    pub fn depth_attr(&self) -> ::openusd::usd::Attribute {
        self.attribute(
            ::openusd::usd::SchemaRegistry::make_multiple_apply_name_instance(
                tokens::SLOT_MULTIPLE_APPLY_TEMPLATE_DEPTH,
                self.name.as_str(),
            ),
        )
    }
    /// The property's declaration, unauthored. Give it a value and
    /// `build` it to author both as one edit; `build` it alone for the
    /// declaration by itself.
    pub fn depth_attr_builder(&self) -> ::openusd::usd::AttributeBuilder<'static> {
        self.attribute_builder(
                ::openusd::usd::SchemaRegistry::make_multiple_apply_name_instance(
                    tokens::SLOT_MULTIPLE_APPLY_TEMPLATE_DEPTH,
                    self.name.as_str(),
                ),
                ::openusd::sdf::ValueTypeName::INT,
            )
            .custom(false)
    }
    /// Authors the property as the schema declares it, and returns it.
    pub fn create_depth_attr(&self) -> ::openusd::Result<::openusd::usd::Attribute> {
        ::std::result::Result::Ok(self.depth_attr_builder().build()?)
    }
    /// Where the slot sits, relative to the prim.
    ///
    /// Declared `double3 slot:__INSTANCE_NAME__:offset = (0.0, 0.0, 0.0)`. Read it
    /// with `get::<::openusd::gf::Vec3d>()`.
    pub fn slot_offset_attr(&self) -> ::openusd::usd::Attribute {
        self.attribute(
            ::openusd::usd::SchemaRegistry::make_multiple_apply_name_instance(
                tokens::SLOT_MULTIPLE_APPLY_TEMPLATE_OFFSET,
                self.name.as_str(),
            ),
        )
    }
    /// The property's declaration, unauthored. Give it a value and
    /// `build` it to author both as one edit; `build` it alone for the
    /// declaration by itself.
    pub fn slot_offset_attr_builder(&self) -> ::openusd::usd::AttributeBuilder<'static> {
        self.attribute_builder(
                ::openusd::usd::SchemaRegistry::make_multiple_apply_name_instance(
                    tokens::SLOT_MULTIPLE_APPLY_TEMPLATE_OFFSET,
                    self.name.as_str(),
                ),
                ::openusd::sdf::ValueTypeName::DOUBLE3,
            )
            .custom(false)
    }
    /// Authors the property as the schema declares it, and returns it.
    pub fn create_slot_offset_attr(
        &self,
    ) -> ::openusd::Result<::openusd::usd::Attribute> {
        ::std::result::Result::Ok(self.slot_offset_attr_builder().build()?)
    }
}

impl ::openusd::usd::SchemaBase for SlotAPI {
    const KIND: ::openusd::usd::SchemaKind = ::openusd::usd::SchemaKind::MultipleApplyApi;
    fn prim(&self) -> &::openusd::usd::Prim {
        &self.prim
    }
}

impl ::std::ops::Deref for SlotAPI {
    type Target = ::openusd::usd::Prim;
    fn deref(&self) -> &Self::Target {
        &self.prim
    }
}

impl ::openusd::usd::APISchemaBase for SlotAPI {}
