// WARNING: THIS FILE IS GENERATED BY openusd-build. DO NOT EDIT.
// Generated from base.usda.

/// The strings this library names things by.
///
/// A token's value is what a stage actually reads; the constant is a
/// name for it, so an application can say what it means instead of
/// retyping a string.
pub mod tokens {
    /// `"owner"`: `ThingAPI`.
    pub const OWNER: &str = "owner";
    /// `"weight"`: `ThingAPI`.
    pub const WEIGHT: &str = "weight";
    /// `"APISchemaBase"`: the schema identifier and family of `APISchemaBase`.
    pub const API_SCHEMA_BASE: &str = "APISchemaBase";
    /// `"ThingAPI"`: the schema identifier and family of `ThingAPI`.
    pub const THING_API: &str = "ThingAPI";
    /// `"Typed"`: the schema identifier and family of `Typed`.
    pub const TYPED: &str = "Typed";
}

/// The library's name, which is the family its declarations register
/// under.
pub const LIBRARY_NAME: &str = "testElsewhere";

/// What this library declares, ready to register: its schemas, and
/// the metadata fields and kinds declared beside them.
///
/// Hand it to
/// [`SchemaRegistryBuilder::register`](::openusd::usd::SchemaRegistryBuilder::register):
/// a stage opened with the resulting registry resolves the fallbacks
/// of the schemas and metadata fields declared here, answers `is_a`
/// along the schemas' inheritance, and counts a declared kind as its
/// base kind. One opened without it knows none of them, so the typed
/// constructors answer `None`.
pub const SCHEMAS: &::openusd::usd::SchemaFamily<'static> = &::openusd::usd::SchemaFamily::new(
    LIBRARY_NAME,
    &[
        ::openusd::usd::SchemaDecl::new(
                "Typed",
                ::openusd::usd::SchemaKind::AbstractBase,
            )
            .bases(&["SchemaBase"]),
        ::openusd::usd::SchemaDecl::new(
                "APISchemaBase",
                ::openusd::usd::SchemaKind::AbstractBase,
            )
            .bases(&["SchemaBase"]),
        ::openusd::usd::SchemaDecl::new(
                "ThingAPI",
                ::openusd::usd::SchemaKind::SingleApplyApi,
            )
            .bases(&["APISchemaBase"])
            .properties(
                &[
                    ::openusd::usd::PropertyDecl::attribute("weight", "double")
                        .varying()
                        .fields(
                            &[
                                ::openusd::usd::Field::new(
                                    "default",
                                    || ::openusd::sdf::Value::Double(1f64),
                                ),
                            ],
                        ),
                    ::openusd::usd::PropertyDecl::relationship("owner").uniform(),
                ],
            ),
    ],
);

/// Marks a prim as a thing, which has a weight and belongs to someone.
#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct ThingAPI(::openusd::usd::Prim);

impl ThingAPI {
    /// Views `prim` as this schema whether or not it carries it.
    ///
    /// Unchecked of the schema, not of memory: nothing here is
    /// `unsafe`, and a prim that does not carry this schema simply
    /// answers nothing for the properties it declares.
    /// [`from_prim`](Self::from_prim) is the constructor that asks.
    pub fn from_prim_unchecked(prim: ::openusd::usd::Prim) -> Self {
        Self(prim)
    }
    /// Applies the schema to `prim` and views it.
    pub fn apply(prim: &::openusd::usd::Prim) -> ::openusd::Result<Self> {
        ::std::result::Result::Ok(Self(prim.clone().apply_api(tokens::THING_API)?))
    }
    /// Whether the schema may be applied to `prim`.
    pub fn can_apply(
        prim: &::openusd::usd::Prim,
    ) -> ::std::result::Result<(), ::openusd::usd::ApplyApiError> {
        prim.can_apply_api(tokens::THING_API)
    }
    /// Views `prim` as this schema, or `None` where it does not carry
    /// it.
    pub fn from_prim(
        prim: ::openusd::usd::Prim,
    ) -> ::openusd::Result<::std::option::Option<Self>> {
        ::std::result::Result::Ok(
            prim.has_api_schema(tokens::THING_API)?.then_some(Self(prim)),
        )
    }
    /// Views the prim at `path` as this schema, or `None` where it does
    /// not carry it — [`from_prim`](Self::from_prim) over the prim
    /// `path` names.
    pub fn get(
        stage: &::openusd::usd::Stage,
        path: impl ::openusd::sdf::IntoPath,
    ) -> ::openusd::Result<::std::option::Option<Self>> {
        Self::from_prim(stage.prim(path)?)
    }
    /// How heavy the thing is.
    ///
    /// Declared `double weight = 1.0`.
    pub fn weight_attr(&self) -> ::openusd::usd::Attribute {
        self.attribute(tokens::WEIGHT)
    }
    /// The property's value at the default time, as the type it is
    /// declared with: what a layer authors, else the fallback the
    /// schema declares.
    pub fn weight(&self) -> ::openusd::Result<::std::option::Option<f64>> {
        self.weight_attr().get::<f64>()
    }
    /// The property's value at `time`, where `None` is the
    /// default time, as the type it is declared with: what a
    /// layer authors there, else the fallback the schema
    /// declares.
    pub fn weight_at(
        &self,
        time: impl ::std::convert::Into<::std::option::Option<::openusd::usd::TimeCode>>,
    ) -> ::openusd::Result<::std::option::Option<f64>> {
        self.weight_attr().get_at::<f64>(time)
    }
    /// The property's declaration, unauthored. Give it a value and
    /// `build` it to author both as one edit; `build` it alone for the
    /// declaration by itself.
    pub fn weight_attr_builder(&self) -> ::openusd::usd::AttributeBuilder<'static> {
        self.attribute_builder(tokens::WEIGHT, ::openusd::sdf::ValueTypeName::DOUBLE)
            .custom(false)
    }
    /// Authors the property as the schema declares it, and returns it.
    pub fn create_weight_attr(&self) -> ::openusd::Result<::openusd::usd::Attribute> {
        ::std::result::Result::Ok(self.weight_attr_builder().build()?)
    }
    /// Whom the thing belongs to.
    ///
    /// Declared `rel owner`.
    pub fn owner_rel(&self) -> ::openusd::usd::Relationship {
        self.relationship(tokens::OWNER)
    }
    /// The property's declaration, unauthored. Give it a value and
    /// `build` it to author both as one edit; `build` it alone for the
    /// declaration by itself.
    pub fn owner_rel_builder(&self) -> ::openusd::usd::RelationshipBuilder<'static> {
        self.relationship_builder(tokens::OWNER).custom(false)
    }
    /// Authors the property as the schema declares it, and returns it.
    pub fn create_owner_rel(&self) -> ::openusd::Result<::openusd::usd::Relationship> {
        ::std::result::Result::Ok(self.owner_rel_builder().build()?)
    }
}

impl ::openusd::usd::SchemaBase for ThingAPI {
    const KIND: ::openusd::usd::SchemaKind = ::openusd::usd::SchemaKind::SingleApplyApi;
    fn prim(&self) -> &::openusd::usd::Prim {
        &self.0
    }
}

impl ::std::ops::Deref for ThingAPI {
    type Target = ::openusd::usd::Prim;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl ::openusd::usd::APISchemaBase for ThingAPI {}
