// WARNING: THIS FILE IS GENERATED BY openusd-build. DO NOT EDIT.
// Generated from schema.usda.

/// The strings this library names things by.
///
/// A token's value is what a stage actually reads; the constant is a
/// name for it, so an application can say what it means instead of
/// retyping a string.
pub mod tokens {
    /// `"badge"`: `BadgeAPI`.
    pub const BADGE: &str = "badge";
    /// `"owner"`: `ThingAPI`.
    pub const OWNER: &str = "owner";
    /// `"volume"`: `Crate`.
    pub const VOLUME: &str = "volume";
    /// `"weight"`: `ThingAPI`.
    pub const WEIGHT: &str = "weight";
    /// `"BadgeAPI"`: the schema identifier and family of `BadgeAPI`.
    pub const BADGE_API: &str = "BadgeAPI";
    /// `"Crate"`: the schema identifier and family of `Crate`.
    pub const CRATE: &str = "Crate";
    /// `"ThingAPI"`: the schema identifier and family of `ThingAPI`.
    pub const THING_API: &str = "ThingAPI";
}

/// The library these schemas belong to, as their manifest records it.
pub const LIBRARY_NAME: &str = "testHere";

/// The schemas this library declares, ready to register.
///
/// Hand it to
/// [`SchemaRegistryBuilder::register`](::openusd::usd::SchemaRegistryBuilder::register):
/// a stage opened with the resulting registry resolves these schemas'
/// fallbacks and answers `is_a` along their inheritance, and one opened
/// without it knows nothing about them, so the typed constructors
/// answer `None`.
pub const SCHEMAS: &::openusd::usd::SchemaFamily<'static> = &::openusd::usd::SchemaFamily::new(
    LIBRARY_NAME,
    &[
        ::openusd::usd::SchemaDecl::new(
                "Crate",
                ::openusd::usd::SchemaKind::ConcreteTyped,
            )
            .bases(&["Typed"])
            .applied_api_schemas(&["ThingAPI"])
            .properties(
                &[
                    ::openusd::usd::PropertyDecl::attribute("volume", "double")
                        .varying()
                        .fields(
                            &[
                                ::openusd::usd::Field::new(
                                    "default",
                                    || ::openusd::sdf::Value::Double(1f64),
                                ),
                            ],
                        ),
                ],
            ),
        ::openusd::usd::SchemaDecl::new(
                "BadgeAPI",
                ::openusd::usd::SchemaKind::SingleApplyApi,
            )
            .bases(&["APISchemaBase"])
            .applied_api_schemas(&["ThingAPI"])
            .properties(
                &[
                    ::openusd::usd::PropertyDecl::attribute("badge", "string")
                        .varying()
                        .fields(&[::openusd::usd::Field::string("default", "")]),
                ],
            ),
    ],
);

/// A box, which is a thing: every crate has a weight and an owner.
///
/// The accessors [`Crate`] carries. They live on a trait so that a schema
/// deriving from this one carries them too.
pub trait CrateSchema: ::openusd::usd::Typed {
    /// Views the prim through [`ThingAPI`](crate::elsewhere::ThingAPI), whose
    /// properties this schema carries.
    fn thing_api(&self) -> crate::elsewhere::ThingAPI {
        crate::elsewhere::ThingAPI::from_prim_unchecked(
            ::openusd::usd::Prim::clone(self.prim()),
        )
    }
    /// How much the crate holds.
    ///
    /// Declared `double volume = 1.0`.
    fn volume_attr(&self) -> ::openusd::usd::Attribute {
        self.prim().attribute(tokens::VOLUME)
    }
    /// The property's value at the default time, as the type it is
    /// declared with: what a layer authors, else the fallback the
    /// schema declares.
    fn volume(&self) -> ::openusd::Result<::std::option::Option<f64>> {
        self.volume_attr().get::<f64>()
    }
    /// The property's value at `time`, where `None` is the
    /// default time, as the type it is declared with: what a
    /// layer authors there, else the fallback the schema
    /// declares.
    fn volume_at(
        &self,
        time: impl ::std::convert::Into<::std::option::Option<::openusd::usd::TimeCode>>,
    ) -> ::openusd::Result<::std::option::Option<f64>> {
        self.volume_attr().get_at::<f64>(time)
    }
    /// The property's declaration, unauthored. Give it a value and
    /// `build` it to author both as one edit; `build` it alone for the
    /// declaration by itself.
    fn volume_attr_builder(&self) -> ::openusd::usd::AttributeBuilder<'static> {
        self.prim()
            .attribute_builder(tokens::VOLUME, ::openusd::sdf::ValueTypeName::DOUBLE)
            .custom(false)
    }
    /// Authors the property as the schema declares it, and returns it.
    fn create_volume_attr(&self) -> ::openusd::Result<::openusd::usd::Attribute> {
        ::std::result::Result::Ok(self.volume_attr_builder().build()?)
    }
    /// How heavy the thing is.
    ///
    /// Declared `double weight = 1.0`.
    fn weight_attr(&self) -> ::openusd::usd::Attribute {
        self.prim().attribute(tokens::WEIGHT)
    }
    /// The property's value at the default time, as the type it is
    /// declared with: what a layer authors, else the fallback the
    /// schema declares.
    fn weight(&self) -> ::openusd::Result<::std::option::Option<f64>> {
        self.weight_attr().get::<f64>()
    }
    /// The property's value at `time`, where `None` is the
    /// default time, as the type it is declared with: what a
    /// layer authors there, else the fallback the schema
    /// declares.
    fn weight_at(
        &self,
        time: impl ::std::convert::Into<::std::option::Option<::openusd::usd::TimeCode>>,
    ) -> ::openusd::Result<::std::option::Option<f64>> {
        self.weight_attr().get_at::<f64>(time)
    }
    /// The property's declaration, unauthored. Give it a value and
    /// `build` it to author both as one edit; `build` it alone for the
    /// declaration by itself.
    fn weight_attr_builder(&self) -> ::openusd::usd::AttributeBuilder<'static> {
        self.prim()
            .attribute_builder(tokens::WEIGHT, ::openusd::sdf::ValueTypeName::DOUBLE)
            .custom(false)
    }
    /// Authors the property as the schema declares it, and returns it.
    fn create_weight_attr(&self) -> ::openusd::Result<::openusd::usd::Attribute> {
        ::std::result::Result::Ok(self.weight_attr_builder().build()?)
    }
    /// Whom the thing belongs to.
    ///
    /// Declared `rel owner`.
    fn owner_rel(&self) -> ::openusd::usd::Relationship {
        self.prim().relationship(tokens::OWNER)
    }
    /// The property's declaration, unauthored. Give it a value and
    /// `build` it to author both as one edit; `build` it alone for the
    /// declaration by itself.
    fn owner_rel_builder(&self) -> ::openusd::usd::RelationshipBuilder<'static> {
        self.prim().relationship_builder(tokens::OWNER).custom(false)
    }
    /// Authors the property as the schema declares it, and returns it.
    fn create_owner_rel(&self) -> ::openusd::Result<::openusd::usd::Relationship> {
        ::std::result::Result::Ok(self.owner_rel_builder().build()?)
    }
}

/// A box, which is a thing: every crate has a weight and an owner.
///
/// # Accessors
///
/// Its accessors live on [`CrateSchema`], which a caller has to have in scope
/// to reach one.
#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct Crate(::openusd::usd::Prim);

impl Crate {
    /// Views `prim` as this schema without asking whether it is one.
    ///
    /// Unchecked of the schema, not of memory: nothing here is
    /// `unsafe`, and a prim of another type simply answers nothing
    /// for the properties this schema declares.
    /// [`from_prim`](Self::from_prim) is the constructor that asks.
    pub fn from_prim_unchecked(prim: ::openusd::usd::Prim) -> Self {
        Self(prim)
    }
    /// Defines a prim of this schema at `path` and views it.
    pub fn define(
        stage: &::openusd::usd::Stage,
        path: impl ::openusd::sdf::IntoPath,
    ) -> ::openusd::Result<Self> {
        ::std::result::Result::Ok(Self(stage.define_typed_prim(path, tokens::CRATE)?))
    }
    /// Views `prim` as this schema, or `None` where it is not one.
    ///
    /// The stage's registry is what answers, so a prim from a stage
    /// opened without this library's family registered is never one.
    pub fn from_prim(
        prim: ::openusd::usd::Prim,
    ) -> ::openusd::Result<::std::option::Option<Self>> {
        ::std::result::Result::Ok(prim.is_a(tokens::CRATE)?.then_some(Self(prim)))
    }
    /// Views the prim at `path` as this schema, or `None` where it
    /// is not one — [`from_prim`](Self::from_prim) over the prim
    /// `path` names.
    pub fn get(
        stage: &::openusd::usd::Stage,
        path: impl ::openusd::sdf::IntoPath,
    ) -> ::openusd::Result<::std::option::Option<Self>> {
        Self::from_prim(stage.prim(path)?)
    }
}

impl ::openusd::usd::SchemaBase for Crate {
    const KIND: ::openusd::usd::SchemaKind = ::openusd::usd::SchemaKind::ConcreteTyped;
    fn prim(&self) -> &::openusd::usd::Prim {
        &self.0
    }
}

impl ::std::ops::Deref for Crate {
    type Target = ::openusd::usd::Prim;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl CrateSchema for Crate {}

impl ::openusd::usd::Typed for Crate {}

/// Labels a prim, and makes it a thing while it is at it.
#[derive(::std::clone::Clone, ::std::fmt::Debug)]
pub struct BadgeAPI(::openusd::usd::Prim);

impl BadgeAPI {
    /// Views `prim` as this schema whether or not it carries it.
    ///
    /// Unchecked of the schema, not of memory: nothing here is
    /// `unsafe`, and a prim that does not carry this schema simply
    /// answers nothing for the properties it declares.
    /// [`from_prim`](Self::from_prim) is the constructor that asks.
    pub fn from_prim_unchecked(prim: ::openusd::usd::Prim) -> Self {
        Self(prim)
    }
    /// Applies the schema to `prim` and views it.
    pub fn apply(prim: &::openusd::usd::Prim) -> ::openusd::Result<Self> {
        ::std::result::Result::Ok(Self(prim.clone().apply_api(tokens::BADGE_API)?))
    }
    /// Whether the schema may be applied to `prim`.
    pub fn can_apply(
        prim: &::openusd::usd::Prim,
    ) -> ::std::result::Result<(), ::openusd::usd::ApplyApiError> {
        prim.can_apply_api(tokens::BADGE_API)
    }
    /// Views `prim` as this schema, or `None` where it does not carry
    /// it.
    pub fn from_prim(
        prim: ::openusd::usd::Prim,
    ) -> ::openusd::Result<::std::option::Option<Self>> {
        ::std::result::Result::Ok(
            prim.has_api_schema(tokens::BADGE_API)?.then_some(Self(prim)),
        )
    }
    /// Views the prim at `path` as this schema, or `None` where it does
    /// not carry it — [`from_prim`](Self::from_prim) over the prim
    /// `path` names.
    pub fn get(
        stage: &::openusd::usd::Stage,
        path: impl ::openusd::sdf::IntoPath,
    ) -> ::openusd::Result<::std::option::Option<Self>> {
        Self::from_prim(stage.prim(path)?)
    }
    /// Views the prim through [`ThingAPI`](crate::elsewhere::ThingAPI), whose
    /// properties this schema carries.
    pub fn thing_api(&self) -> crate::elsewhere::ThingAPI {
        crate::elsewhere::ThingAPI::from_prim_unchecked(
            ::openusd::usd::Prim::clone(self),
        )
    }
    /// What the label says.
    ///
    /// Declared `string badge = ""`.
    pub fn badge_attr(&self) -> ::openusd::usd::Attribute {
        self.attribute(tokens::BADGE)
    }
    /// The property's value at the default time, as the type it is
    /// declared with: what a layer authors, else the fallback the
    /// schema declares.
    pub fn badge(
        &self,
    ) -> ::openusd::Result<::std::option::Option<::std::string::String>> {
        self.badge_attr().get::<::std::string::String>()
    }
    /// The property's value at `time`, where `None` is the
    /// default time, as the type it is declared with: what a
    /// layer authors there, else the fallback the schema
    /// declares.
    pub fn badge_at(
        &self,
        time: impl ::std::convert::Into<::std::option::Option<::openusd::usd::TimeCode>>,
    ) -> ::openusd::Result<::std::option::Option<::std::string::String>> {
        self.badge_attr().get_at::<::std::string::String>(time)
    }
    /// The property's declaration, unauthored. Give it a value and
    /// `build` it to author both as one edit; `build` it alone for the
    /// declaration by itself.
    pub fn badge_attr_builder(&self) -> ::openusd::usd::AttributeBuilder<'static> {
        self.attribute_builder(tokens::BADGE, ::openusd::sdf::ValueTypeName::STRING)
            .custom(false)
    }
    /// Authors the property as the schema declares it, and returns it.
    pub fn create_badge_attr(&self) -> ::openusd::Result<::openusd::usd::Attribute> {
        ::std::result::Result::Ok(self.badge_attr_builder().build()?)
    }
    /// How heavy the thing is.
    ///
    /// Declared `double weight = 1.0`.
    pub fn weight_attr(&self) -> ::openusd::usd::Attribute {
        self.attribute(tokens::WEIGHT)
    }
    /// The property's value at the default time, as the type it is
    /// declared with: what a layer authors, else the fallback the
    /// schema declares.
    pub fn weight(&self) -> ::openusd::Result<::std::option::Option<f64>> {
        self.weight_attr().get::<f64>()
    }
    /// The property's value at `time`, where `None` is the
    /// default time, as the type it is declared with: what a
    /// layer authors there, else the fallback the schema
    /// declares.
    pub fn weight_at(
        &self,
        time: impl ::std::convert::Into<::std::option::Option<::openusd::usd::TimeCode>>,
    ) -> ::openusd::Result<::std::option::Option<f64>> {
        self.weight_attr().get_at::<f64>(time)
    }
    /// The property's declaration, unauthored. Give it a value and
    /// `build` it to author both as one edit; `build` it alone for the
    /// declaration by itself.
    pub fn weight_attr_builder(&self) -> ::openusd::usd::AttributeBuilder<'static> {
        self.attribute_builder(tokens::WEIGHT, ::openusd::sdf::ValueTypeName::DOUBLE)
            .custom(false)
    }
    /// Authors the property as the schema declares it, and returns it.
    pub fn create_weight_attr(&self) -> ::openusd::Result<::openusd::usd::Attribute> {
        ::std::result::Result::Ok(self.weight_attr_builder().build()?)
    }
    /// Whom the thing belongs to.
    ///
    /// Declared `rel owner`.
    pub fn owner_rel(&self) -> ::openusd::usd::Relationship {
        self.relationship(tokens::OWNER)
    }
    /// The property's declaration, unauthored. Give it a value and
    /// `build` it to author both as one edit; `build` it alone for the
    /// declaration by itself.
    pub fn owner_rel_builder(&self) -> ::openusd::usd::RelationshipBuilder<'static> {
        self.relationship_builder(tokens::OWNER).custom(false)
    }
    /// Authors the property as the schema declares it, and returns it.
    pub fn create_owner_rel(&self) -> ::openusd::Result<::openusd::usd::Relationship> {
        ::std::result::Result::Ok(self.owner_rel_builder().build()?)
    }
}

impl ::openusd::usd::SchemaBase for BadgeAPI {
    const KIND: ::openusd::usd::SchemaKind = ::openusd::usd::SchemaKind::SingleApplyApi;
    fn prim(&self) -> &::openusd::usd::Prim {
        &self.0
    }
}

impl ::std::ops::Deref for BadgeAPI {
    type Target = ::openusd::usd::Prim;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl ::openusd::usd::APISchemaBase for BadgeAPI {}
