//! The Rust a schema library is generated as.
//!
//! [`lower`] settles every name a schema implies — what each type and trait is
//! called, which traits a view implements, which accessors it offers — and is
//! the only place that does, so a name is decided once and can be checked for
//! collisions there. [`emitter`] writes the views from that, [`family`] writes
//! the schema data from the declarations beside it, and [`render`] lays the
//! result out as text.
//!
//! The file is written to be included bare into whatever module a consumer
//! chooses, through `openusd::include_schema!`. That is what decides its shape:
//! it carries no `use` block, since one would apply to the module it lands in
//! and could collide with what the consumer already imports, so every path in it
//! is spelled in full.

mod emitter;
mod family;
mod lower;
mod value;

use proc_macro2::{Ident, Span, TokenStream};

use crate::Views;
use crate::decl;
use crate::model::Library;
use crate::{Externs, error::Error};

/// One library's generated file, `schema` naming what it came from.
///
/// With [`Views::Skip`] it carries the tokens and the schema data alone, which is
/// what a library asking for `skipCodeGeneration` wants and what a crate whose
/// API is written by hand asks for through
/// [`Builder::schema_data`](crate::Builder::schema_data). The data is not
/// optional either way: it is what a registry is built from, so a file without
/// it would leave the schemas unregisterable.
pub fn emit(model: &Library, externs: &Externs, schema: &str, views: Views) -> Result<String, Error> {
    let lowered = match views {
        Views::Generate => lower::library(model, externs)?,
        Views::Skip => lower::tokens(model)?,
    };
    let declarations = decl::with_family(model, family::declarations)?;
    render(emitter::library(&lowered, &declarations), schema)
}

/// The items the generated file declares at its top level, by name.
///
/// [`emitter`] and [`family`] write them under these names and [`lower`]
/// refuses a schema that would reach one, so the two cannot disagree about what
/// is taken: a name added or renamed here changes both.
pub(super) mod items {
    /// The module holding the token constants.
    pub const TOKENS: &str = "tokens";
    /// The constant naming the library.
    pub const LIBRARY_NAME: &str = "LIBRARY_NAME";
    /// The constant holding the declarations a registry takes.
    pub const SCHEMAS: &str = "SCHEMAS";

    /// All of them, for the collision check.
    pub const ALL: [&str; 3] = [TOKENS, LIBRARY_NAME, SCHEMAS];
}

/// One generated item, by the name it is written under.
fn ident(name: &str) -> Ident {
    Ident::new(name, Span::call_site())
}

/// The header every generated file opens with, as upstream marks its own.
const GENERATED_BY: &str = "WARNING: THIS FILE IS GENERATED BY openusd-build. DO NOT EDIT.";

/// The tokens as a formatted file, with the header above them.
///
/// Each top-level item is laid out on its own so that a blank line falls
/// between them: `prettyplease` reads a syntax tree, which has no blank lines of
/// its own to keep.
fn render(file: TokenStream, schema: &str) -> Result<String, Error> {
    let parsed: syn::File = syn::parse2(file).map_err(|cause| Error::Malformed {
        schema: schema.to_owned(),
        cause: cause.to_string(),
    })?;
    let items: Vec<String> = parsed
        .items
        .into_iter()
        .map(|item| {
            let one = syn::File {
                shebang: None,
                attrs: Vec::new(),
                items: vec![item],
            };
            prettyplease::unparse(&one)
        })
        .collect();

    Ok(format!(
        "// {GENERATED_BY}\n// Generated from {schema}.\n\n{}",
        items.join("\n")
    ))
}

#[cfg(test)]
mod tests {
    use std::path::Path;
    use std::sync::LazyLock;

    use super::*;
    use crate::configure;
    use crate::error::Error;
    use crate::tests::read_source;
    use crate::validate::Violation;

    /// A library covering the kinds that emit differently.
    const KINDS: &str = r#"#usda 1.0

def "GLOBAL" (
    customData = {
        string libraryName = "testEmit"
    }
)
{
}

class "Typed" {}

class "APISchemaBase" {}

class "Shape" (
    inherits = </Typed>
) {
    color3f color = (1, 1, 1)
}

class Ball "Ball" (
    inherits = </Shape>
) {
    double radius = 1
}

class "TagAPI" (
    inherits = </APISchemaBase>
    customData = {
        token apiSchemaType = "singleApply"
    }
) {
    string tag = ""
}

class "SlotAPI" (
    inherits = </APISchemaBase>
    customData = {
        token apiSchemaType = "multipleApply"
        token propertyNamespacePrefix = "slot"
    }
) {
    int depth = 0
}
"#;

    /// A library whose accessors exercise the shapes that differ.
    const ACCESSORS: &str = r#"#usda 1.0

def "GLOBAL" (
    customData = {
        string libraryName = "testAccessors"
    }
)
{
}

class "Typed" {}

class "Held" (
    inherits = </Typed>
) {
    double radius = 1 (
        doc = "The radius."
    )
    uniform token mode = "a" (
        allowedTokens = ["a", "b"]
    )
    custom float temp
    rel target
    int hidden (
        customData = {
            string apiName = ""
        }
    )
}
"#;

    /// A library declaring a versioned spelling of a schema root.
    const VERSIONED_ROOT: &str = r#"#usda 1.0

def "GLOBAL" (
    customData = {
        string libraryName = "testRoot"
    }
)
{
}

class "Typed" {}

class "Typed_1" {}
"#;

    /// The body of a view's inherent `impl` block, which is where its
    /// constructors are written.
    fn impl_block<'a>(text: &'a str, name: &str) -> &'a str {
        let opened = format!("impl {name} {{");
        let (_, rest) = text
            .split_once(&opened)
            .unwrap_or_else(|| panic!("{name} has an impl block"));
        let (body, _) = rest
            .split_once(
                "
}",
            )
            .unwrap_or_else(|| panic!("{name}'s impl block ends"));
        body
    }

    /// A library whose documentation points at its own API, the way upstream's
    /// does.
    const REFERENCES: &str = r#"#usda 1.0

def "GLOBAL" (
    customData = {
        string libraryName = "testRefs"
    }
)
{
}

class "Typed" {}

class RefsCrate "RefsCrate" (
    doc = """A TestRefsCrate holds a TestRefsBox.
    See GetWeightAttr(), GetSizeAttr() and TestRefsBox::GetSizeAttr()."""
    inherits = </Typed>
    customData = {
        string className = "Crate"
    }
) {
}

class Tin "Tin" (
    doc = "Another thing with a size."
    inherits = </Typed>
) {
    double size = 1
}

class Box "Box" (
    doc = """A TestRefsBox, which knows its own size.
    \\sa GetSizeAttr()
    \\sa ComputeNothing()"""
    inherits = </Typed>
) {
    double size = 1
    double weight = 1
}
"#;

    /// What one schema library generates.
    fn emitted(source: &str) -> String {
        let dir = tempfile::tempdir().expect("tempdir");
        let model = read_source(dir.path(), source).expect("resolves");
        emit(&model, &Externs::new(), "schema.usda", Views::Generate).expect("emits")
    }

    /// The kinds fixture, emitted once for the tests that read it.
    fn kinds() -> &'static str {
        static ONCE: LazyLock<String> = LazyLock::new(|| emitted(KINDS));
        &ONCE
    }

    /// The accessors fixture, likewise.
    fn accessors() -> &'static str {
        static ONCE: LazyLock<String> = LazyLock::new(|| emitted(ACCESSORS));
        &ONCE
    }

    /// The references fixture, likewise.
    fn references() -> &'static str {
        static ONCE: LazyLock<String> = LazyLock::new(|| emitted(REFERENCES));
        &ONCE
    }

    /// The values fixture, likewise. It lives as a file because
    /// `tests/values.rs` compiles what it generates.
    fn values() -> &'static str {
        static ONCE: LazyLock<String> = LazyLock::new(|| {
            let dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("fixtures/values");
            let library = configure()
                .search_path(&dir)
                .read(&dir.join("schema.usda"))
                .map(|(library, _)| library)
                .expect("the values fixture resolves");
            emit(&library, &Externs::new(), "schema.usda", Views::Generate).expect("emits")
        });
        &ONCE
    }

    /// Every value a schema can declare reaches the table, dictionaries and
    /// the matrix types whose `gf` names differ from their variants included.
    /// A value with no literal stops the build, so this passing is what says
    /// the writer covers what a schema can say.
    #[test]
    fn every_value_written() {
        let text = values();
        for expected in [
            // A dictionary, written in key order and holding a value of its own.
            "::openusd::sdf::Dictionary::from(",
            "::openusd::sdf::Value::DoubleVec(",
            // The three matrices, each through the `gf` type that carries it.
            "::openusd::gf::Mat2d([",
            "::openusd::gf::Mat3d([",
            "::openusd::gf::Matrix4d([",
            "::openusd::gf::quath(",
            "::openusd::sdf::TimeCode(",
            "::openusd::gf::f16::from_bits(",
            "::openusd::sdf::AssetPath::new(",
            // A blocked default is a value, not a missing one.
            "::openusd::sdf::Value::ValueBlock",
            // A bare `rel` is uniform and a `varying rel` is not, and each is
            // written as whichever differs from the constructor's own default.
            "::openusd::usd::PropertyDecl::relationship(\"plain\")",
            "::openusd::usd::PropertyDecl::relationship(\"loose\").varying()",
        ] {
            assert!(text.contains(expected), "{expected} is missing from:\n{text}");
        }
    }

    /// Every schema is a view struct under its own name plus the trait its own
    /// accessors live on, abstract and concrete alike, and a view derives from
    /// the trait of each class behind it.
    #[test]
    fn kinds_take_their_shapes() {
        let text = kinds();
        assert!(
            text.contains("pub trait ShapeSchema: ::openusd::usd::Typed {"),
            "{text}"
        );
        assert!(text.contains("pub trait BallSchema: ShapeSchema {"), "{text}");
        assert!(text.contains("pub struct Shape(::openusd::usd::Prim);"), "{text}");
        assert!(text.contains("pub struct Ball(::openusd::usd::Prim);"), "{text}");
        assert!(text.contains("impl BallSchema for Ball {}"), "{text}");
        assert!(text.contains("impl ShapeSchema for Ball {}"), "{text}");
        assert!(text.contains("impl ::openusd::usd::Typed for Shape {}"), "{text}");
    }

    /// An abstract schema names no type a prim can be defined as, so its view
    /// recognises a prim without defining one.
    #[test]
    fn abstract_constructors() {
        let text = kinds();
        assert!(
            text.contains("prim.is_a(tokens::SHAPE)?.then_some(Self(prim))"),
            "{text}"
        );
        assert!(!impl_block(text, "Shape").contains("fn define"), "{text}");
    }

    /// A concrete view is a prim type, so it defines and recognises one.
    #[test]
    fn concrete_constructors() {
        let text = kinds();
        assert!(text.contains("stage.define_typed_prim(path, tokens::BALL)?"), "{text}");
        assert!(
            text.contains("prim.is_a(tokens::BALL)?.then_some(Self(prim))"),
            "{text}"
        );
    }

    /// An applied API schema is applied rather than defined, and a
    /// multiple-apply one carries the instance name it was applied under.
    #[test]
    fn applied_constructors() {
        let text = kinds();
        assert!(text.contains("prim.clone().apply_api(tokens::TAG_API)?"), "{text}");
        assert!(text.contains("name: ::openusd::tf::Token,"), "{text}");
        assert!(text.contains("make_applied_name(tokens::SLOT_API"), "{text}");
    }

    /// A multiple-apply schema's properties are templates, so its accessors put
    /// the view's own instance name into one.
    #[test]
    fn instanced_accessors() {
        let text = kinds();
        assert!(
            text.contains("make_multiple_apply_name_instance("),
            "the template is instantiated: {text}"
        );
        assert!(text.contains("tokens::SLOT_MULTIPLE_APPLY_TEMPLATE_DEPTH"), "{text}");
        assert!(text.contains("self.name.as_str()"), "{text}");
    }

    /// The file carries no `use` block, every path being spelled in full, since
    /// it is included into a module it knows nothing about.
    #[test]
    fn no_imports() {
        let text = kinds();
        assert!(!text.contains("\nuse "), "{text}");
    }

    /// The schema data is a declaration table, so registering a family reads
    /// no file and parses nothing.
    #[test]
    fn schema_data_is_declared() {
        let text = kinds();
        assert!(text.contains("pub const LIBRARY_NAME: &str = \"testEmit\";"), "{text}");
        assert!(
            text.contains("pub const SCHEMAS: &::openusd::usd::SchemaFamily<'static>"),
            "{text}"
        );
        assert!(text.contains("::openusd::usd::SchemaDecl::new("), "{text}");
        assert!(text.contains("::openusd::usd::SchemaKind::ConcreteTyped"), "{text}");
        assert!(
            text.contains("::openusd::usd::PropertyDecl::attribute(\"radius\", \"double\")"),
            "{text}"
        );
        assert!(!text.contains("include_bytes!"), "{text}");
    }

    /// A reader reaches the property, and the creator declares it with the type
    /// the schema gave it.
    #[test]
    fn attribute_pair() {
        let text = accessors();
        assert!(
            text.contains("fn radius_attr(&self) -> ::openusd::usd::Attribute {"),
            "{text}"
        );
        assert!(text.contains("self.prim().attribute(tokens::RADIUS)"), "{text}");
        assert!(text.contains("::openusd::sdf::ValueTypeName::DOUBLE"), "{text}");
    }

    /// What the schema declared is what the creator authors. Authoring leaves a
    /// property `custom`, so every creator says whether it is one; a uniform
    /// property says that too.
    #[test]
    fn creator_authors_declaration() {
        let text = accessors();
        assert!(text.contains(".set_custom(true)?"), "{text}");
        assert!(text.contains(".set_custom(false)?"), "{text}");
        assert!(
            text.contains(".set_variability(::openusd::sdf::Variability::Uniform)?"),
            "{text}"
        );
    }

    /// A relationship reads as a relationship, not as an attribute.
    #[test]
    fn relationship_pair() {
        let text = accessors();
        assert!(
            text.contains("fn target_rel(&self) -> ::openusd::usd::Relationship {"),
            "{text}"
        );
        assert!(text.contains("create_relationship(tokens::TARGET)?"), "{text}");
    }

    /// An empty `apiName` asks for no accessor, so none is written.
    #[test]
    fn suppressed_has_none() {
        let text = accessors();
        assert!(!text.contains("fn hidden"), "{text}");
    }

    /// The documentation says what the property is, beyond what the schema
    /// wrote about it, and the declaration is the one `sdf` would write.
    #[test]
    fn documents_the_declaration() {
        let text = accessors();
        assert!(text.contains("The radius."), "{text}");
        assert!(text.contains("Declared `double radius = 1.0`."), "{text}");
        assert!(text.contains("Read it with `get::<f64>()`"), "{text}");
        assert!(
            text.contains("Declared `uniform token mode = \"a\"`. One of `a`, `b`."),
            "{text}"
        );
    }

    /// Two token identifiers can reach one Rust constant, which upstream does
    /// on purpose where a schema and a property share a name. The library
    /// declares the pair happily, and the second constant takes an underscore.
    #[test]
    fn two_ids_one_constant() {
        let dir = tempfile::tempdir().expect("tempdir");
        let library = read_source(
            dir.path(),
            r#"#usda 1.0

def "GLOBAL" (
    customData = {
        string libraryName = "testConstants"
        dictionary libraryTokens = {
            dictionary drawMode = {
                string value = "a"
            }
            dictionary draw_mode = {
                string value = "b"
            }
        }
    }
)
{
}

class "Typed" {}
"#,
        )
        .expect("the library itself is well formed");

        let text = emit(&library, &Externs::new(), "schema.usda", Views::Generate).expect("both are named");
        // `draw_mode` sorts before `drawMode`, so it is the one that keeps the
        // name; both say which string they hold.
        assert!(text.contains("pub const DRAW_MODE: &str = \"b\";"), "{text}");
        assert!(text.contains("pub const DRAW_MODE_: &str = \"a\";"), "{text}");
    }

    /// Two properties of one class can ask for one accessor name, and Rust has
    /// no way to hold both.
    #[test]
    fn two_properties_one_method() {
        let dir = tempfile::tempdir().expect("tempdir");
        let library = read_source(
            dir.path(),
            r#"#usda 1.0

def "GLOBAL" (
    customData = {
        string libraryName = "testMethods"
    }
)
{
}

class "Typed" {}

class "Held" (
    inherits = </Typed>
) {
    int one (
        customData = {
            string apiName = "same"
        }
    )
    int two (
        customData = {
            string apiName = "same"
        }
    )
}
"#,
        )
        .expect("the library itself is well formed");

        match emit(&library, &Externs::new(), "schema.usda", Views::Generate) {
            Err(Error::Definition {
                violation: Violation::MethodCollision { method, .. },
                ..
            }) => assert_eq!(method, "same_attr"),
            other => panic!("{:?}", other.map(|_| "emitted")),
        }
    }

    /// A schema may call its class anything USD admits, including a word Rust
    /// has taken, which is refused where it is named rather than where it is
    /// written out.
    #[test]
    fn keyword_class_name() {
        let dir = tempfile::tempdir().expect("tempdir");
        let library = read_source(
            dir.path(),
            r#"#usda 1.0

def "GLOBAL" (
    customData = {
        string libraryName = "testKeywords"
    }
)
{
}

class "Typed" {}

class "Held" (
    inherits = </Typed>
    customData = {
        string className = "type"
    }
) {
}
"#,
        )
        .expect("the library itself is well formed");

        match emit(&library, &Externs::new(), "schema.usda", Views::Generate) {
            Err(Error::Definition {
                violation: Violation::NotAnIdentifier { name },
                ..
            }) => assert_eq!(name, "type"),
            other => panic!("{:?}", other.map(|_| "emitted")),
        }
    }

    /// The schema roots are the core's own traits, so a library that declares
    /// one — as the core `usd` library itself does — generates nothing for it.
    #[test]
    fn roots_are_not_generated() {
        let text = kinds();
        assert!(!text.contains("trait Typed"), "{text}");
        assert!(!text.contains("trait APISchemaBase"), "{text}");
        assert!(
            text.contains("::openusd::usd::Typed"),
            "the core's is what a view answers to: {text}"
        );
    }

    /// A reference upstream wrote about its own API reads as a link to
    /// whatever answers for it here; one to something only C++ has keeps the
    /// name it was written with.
    #[test]
    fn references_become_links() {
        let text = references();
        assert!(text.contains("[`size_attr`](BoxSchema::size_attr)"), "{text}");
        assert!(text.contains("[`Box`]"), "{text}");
        assert!(text.contains("`ComputeNothing()`"), "{text}");
    }

    /// Upstream names a class by the class name it declared, not by the
    /// identifier it is registered under, so that is what the C++ spelling is
    /// built from: `RefsCrate` is `TestRefsCrate` there and `Crate` here.
    #[test]
    fn class_name_builds_symbol() {
        let text = references();
        assert!(text.contains("A [`Crate`] holds a [`Box`]."), "{text}");
    }

    /// A name reached from outside the declaring class's chain is answered by
    /// the library, which pairs a name only one class declares. `Crate` is
    /// under neither `Box` nor `Tin`, and both declare a `size`.
    #[test]
    fn library_answers_unique_names() {
        let text = references();
        // The sentence wraps, so it is read whole rather than by line, and to
        // wherever the paragraph it is in ends.
        let at = text.find("See [").expect("the sentence that references them");
        let rest = &text[at..];
        let sentence = rest.split_once("\n    ///\n").map_or(rest, |(paragraph, _)| paragraph);
        assert!(
            sentence.contains("[`weight_attr`](BoxSchema::weight_attr)"),
            "{sentence}"
        );
        assert!(
            sentence.contains("`GetSizeAttr()`"),
            "ambiguous, so left alone: {sentence}"
        );
        assert!(
            sentence.contains("[`size_attr`](BoxSchema::size_attr)"),
            "qualified, so answered: {sentence}"
        );
    }

    /// Rootness is one question with one answer: a versioned spelling names the
    /// same family, so the rule that classifies it and the filter that skips it
    /// reach the same verdict and it is generated no more than `Typed` is.
    #[test]
    fn versioned_root_not_generated() {
        let text = emitted(VERSIONED_ROOT);
        assert!(text.contains("pub const LIBRARY_NAME"), "the library emits: {text}");
        assert!(!text.contains("pub trait"), "{text}");
        assert!(!text.contains("pub struct"), "{text}");
    }

    /// The generated file takes three names of its own, and a class that asks
    /// for one is refused where it asks rather than by the consumer's compiler.
    #[test]
    fn class_takes_a_file_name() {
        let dir = tempfile::tempdir().expect("tempdir");
        let library = read_source(
            dir.path(),
            r#"#usda 1.0

def "GLOBAL" (
    customData = {
        string libraryName = "testReserved"
    }
)
{
}

class "Typed" {}

class "Held" (
    inherits = </Typed>
    customData = {
        string className = "tokens"
    }
) {
}
"#,
        )
        .expect("the library itself is well formed");

        match emit(&library, &Externs::new(), "schema.usda", Views::Generate) {
            Err(Error::Definition {
                violation: Violation::RustNameCollision { name, .. },
                ..
            }) => assert_eq!(name, "tokens"),
            other => panic!("{:?}", other.map(|_| "emitted")),
        }
    }

    /// A legacy type spelling a stage resolves but no constant names is one no
    /// creator could declare, so it is refused rather than declared as a token.
    #[test]
    fn type_without_a_constant() {
        let dir = tempfile::tempdir().expect("tempdir");
        let library = read_source(
            dir.path(),
            r#"#usda 1.0

def "GLOBAL" (
    customData = {
        string libraryName = "testTypes"
    }
)
{
}

class "Typed" {}

class "Held" (
    inherits = </Typed>
) {
    Transform placement
}
"#,
        )
        .expect("the type is one a stage resolves");

        match emit(&library, &Externs::new(), "schema.usda", Views::Generate) {
            Err(Error::Definition {
                violation: Violation::UnnameableType { property, .. },
                ..
            }) => assert_eq!(property.as_str(), "placement"),
            other => panic!("{:?}", other.map(|_| "emitted")),
        }
    }

    /// A redeclaration reaches the ancestor's accessor, so a hand-written
    /// reader asked for beside it would never be called.
    #[test]
    fn custom_get_on_a_redeclaration() {
        let dir = tempfile::tempdir().expect("tempdir");
        let library = read_source(
            dir.path(),
            r#"#usda 1.0

def "GLOBAL" (
    customData = {
        string libraryName = "testShadowed"
    }
)
{
}

class "Typed" {}

class "Held" (
    inherits = </Typed>
) {
    double size = 1
}

class "Deeper" (
    inherits = </Held>
) {
    double size = 2 (
        customData = {
            string apiGetImplementation = "custom"
        }
    )
}
"#,
        )
        .expect("the library itself is well formed");

        match emit(&library, &Externs::new(), "schema.usda", Views::Generate) {
            Err(Error::Definition {
                violation: Violation::CustomGetWithoutAccessor { property },
                ..
            }) => assert_eq!(property.as_str(), "size"),
            other => panic!("{:?}", other.map(|_| "emitted")),
        }
    }
}
