// WARNING: THIS FILE IS GENERATED BY openusd-build. DO NOT EDIT.
// Generated from shaderDefs.usda.

/// The strings this library names things by.
///
/// A token's value is what a stage actually reads; the constant is a
/// name for it, so an application can say what it means instead of
/// retyping a string.
pub mod tokens {
    /// `"UsdTinyReader_float2"`: the `info:id` of a `UsdTinyReader_float2` shader.
    pub const USD_TINY_READER_FLOAT2: &str = "UsdTinyReader_float2";
    /// `"UsdTinySurface"`: the `info:id` of a `UsdTinySurface` shader.
    pub const USD_TINY_SURFACE: &str = "UsdTinySurface";
    /// `"in"`: an input or output a shader node declares.
    pub const IN_: &str = "in";
    /// `"mode"`: an input or output a shader node declares.
    pub const MODE: &str = "mode";
    /// `"result"`: an input or output a shader node declares.
    pub const RESULT: &str = "result";
    /// `"surface"`: an input or output a shader node declares.
    pub const SURFACE: &str = "surface";
    /// `"tint"`: an input or output a shader node declares.
    pub const TINT: &str = "tint";
    /// `"varname"`: an input or output a shader node declares.
    pub const VARNAME: &str = "varname";
}

/// A surface with one colour and a mode.
///
/// A `Shader` whose `info:id` is `UsdTinySurface`, as the `tinyNodes` library
/// defines the node.
#[derive(::std::fmt::Debug, ::std::clone::Clone)]
pub struct TinySurface(crate::shade::Shader);

impl TinySurface {
    /// The `info:id` a shader of this node authors.
    pub const ID: &str = tokens::USD_TINY_SURFACE;
    /// Views `shader` as this node, or `None` where it authors another
    /// `info:id`.
    pub fn from_shader(
        shader: crate::shade::Shader,
    ) -> ::openusd::Result<::std::option::Option<Self>> {
        ::std::result::Result::Ok(
            (shader.id()?.as_deref() == ::std::option::Option::Some(Self::ID))
                .then_some(Self(shader)),
        )
    }
    /// Views the prim at `path` as this node, or `None` where it is not
    /// a `Shader` of this node's `info:id`.
    pub fn get(
        stage: &::openusd::usd::Stage,
        path: impl ::openusd::sdf::IntoPath,
    ) -> ::openusd::Result<::std::option::Option<Self>> {
        match crate::shade::Shader::get(stage, path)? {
            ::std::option::Option::Some(shader) => Self::from_shader(shader),
            ::std::option::Option::None => {
                ::std::result::Result::Ok(::std::option::Option::None)
            }
        }
    }
    /// Defines a `Shader` at `path` authoring this node's `info:id`,
    /// and views it.
    pub fn define(
        stage: &::openusd::usd::Stage,
        path: impl ::openusd::sdf::IntoPath,
    ) -> ::openusd::Result<Self> {
        let shader = crate::shade::Shader::define(stage, path)?;
        shader.create_id_attr()?.set(::openusd::sdf::Value::token(Self::ID))?;
        ::std::result::Result::Ok(Self(shader))
    }
    /// The `Shader` this node is.
    pub fn shader(&self) -> &crate::shade::Shader {
        &self.0
    }
    /// The surface's colour.
    ///
    /// Declared `color3f inputs:tint = (0.5, 0.5, 0.5)`.
    pub fn tint_input(&self) -> crate::shade::Input {
        <crate::shade::Shader as crate::shade::Connectable>::input(&self.0, tokens::TINT)
    }
    /// The input's value as the type it is declared with: what the
    /// shader authors, else the value the node's definition gives it.
    pub fn tint(
        &self,
    ) -> ::openusd::Result<::std::option::Option<::openusd::gf::Vec3f>> {
        match self.tint_input().attribute().get::<::openusd::gf::Vec3f>()? {
            ::std::option::Option::Some(value) => {
                ::std::result::Result::Ok(::std::option::Option::Some(value))
            }
            ::std::option::Option::None => {
                <::openusd::gf::Vec3f as ::std::convert::TryFrom<
                    ::openusd::sdf::Value,
                >>::try_from(
                        ::openusd::sdf::Value::Vec3f(
                            ::openusd::gf::vec3f(0.5f32, 0.5f32, 0.5f32),
                        ),
                    )
                    .map(::std::option::Option::Some)
                    .map_err(::std::convert::Into::into)
            }
        }
    }
    /// Declared `token inputs:mode = "matte"`. One of `matte`, `gloss`. It connects
    /// only to an interface input.
    pub fn mode_input(&self) -> crate::shade::Input {
        <crate::shade::Shader as crate::shade::Connectable>::input(&self.0, tokens::MODE)
    }
    /// The input's value as the type it is declared with: what the
    /// shader authors, else the value the node's definition gives it.
    pub fn mode(
        &self,
    ) -> ::openusd::Result<::std::option::Option<::openusd::tf::Token>> {
        match self.mode_input().attribute().get::<::openusd::tf::Token>()? {
            ::std::option::Option::Some(value) => {
                ::std::result::Result::Ok(::std::option::Option::Some(value))
            }
            ::std::option::Option::None => {
                <::openusd::tf::Token as ::std::convert::TryFrom<
                    ::openusd::sdf::Value,
                >>::try_from(::openusd::sdf::Value::token("matte"))
                    .map(::std::option::Option::Some)
                    .map_err(::std::convert::Into::into)
            }
        }
    }
    /// Declared `token outputs:surface`.
    pub fn surface_output(&self) -> crate::shade::Output {
        <crate::shade::Shader as crate::shade::Connectable>::output(
            &self.0,
            tokens::SURFACE,
        )
    }
}

/// Reads a two-component primvar.
///
/// A `Shader` whose `info:id` is `UsdTinyReader_float2`, as the `tinyNodes`
/// library defines the node.
#[derive(::std::fmt::Debug, ::std::clone::Clone)]
pub struct TinyReaderFloat2(crate::shade::Shader);

impl TinyReaderFloat2 {
    /// The `info:id` a shader of this node authors.
    pub const ID: &str = tokens::USD_TINY_READER_FLOAT2;
    /// Views `shader` as this node, or `None` where it authors another
    /// `info:id`.
    pub fn from_shader(
        shader: crate::shade::Shader,
    ) -> ::openusd::Result<::std::option::Option<Self>> {
        ::std::result::Result::Ok(
            (shader.id()?.as_deref() == ::std::option::Option::Some(Self::ID))
                .then_some(Self(shader)),
        )
    }
    /// Views the prim at `path` as this node, or `None` where it is not
    /// a `Shader` of this node's `info:id`.
    pub fn get(
        stage: &::openusd::usd::Stage,
        path: impl ::openusd::sdf::IntoPath,
    ) -> ::openusd::Result<::std::option::Option<Self>> {
        match crate::shade::Shader::get(stage, path)? {
            ::std::option::Option::Some(shader) => Self::from_shader(shader),
            ::std::option::Option::None => {
                ::std::result::Result::Ok(::std::option::Option::None)
            }
        }
    }
    /// Defines a `Shader` at `path` authoring this node's `info:id`,
    /// and views it.
    pub fn define(
        stage: &::openusd::usd::Stage,
        path: impl ::openusd::sdf::IntoPath,
    ) -> ::openusd::Result<Self> {
        let shader = crate::shade::Shader::define(stage, path)?;
        shader.create_id_attr()?.set(::openusd::sdf::Value::token(Self::ID))?;
        ::std::result::Result::Ok(Self(shader))
    }
    /// The `Shader` this node is.
    pub fn shader(&self) -> &crate::shade::Shader {
        &self.0
    }
    /// Declared `string inputs:varname`.
    pub fn varname_input(&self) -> crate::shade::Input {
        <crate::shade::Shader as crate::shade::Connectable>::input(
            &self.0,
            tokens::VARNAME,
        )
    }
    /// The input's value as the type it is declared with: what the
    /// shader authors, else the value the node's definition gives it.
    pub fn varname(
        &self,
    ) -> ::openusd::Result<::std::option::Option<::std::string::String>> {
        self.varname_input().attribute().get::<::std::string::String>()
    }
    /// Declared `float2 inputs:in = (0.0, 0.0)`.
    pub fn in_input(&self) -> crate::shade::Input {
        <crate::shade::Shader as crate::shade::Connectable>::input(&self.0, tokens::IN_)
    }
    /// The input's value as the type it is declared with: what the
    /// shader authors, else the value the node's definition gives it.
    pub fn in_(&self) -> ::openusd::Result<::std::option::Option<::openusd::gf::Vec2f>> {
        match self.in_input().attribute().get::<::openusd::gf::Vec2f>()? {
            ::std::option::Option::Some(value) => {
                ::std::result::Result::Ok(::std::option::Option::Some(value))
            }
            ::std::option::Option::None => {
                <::openusd::gf::Vec2f as ::std::convert::TryFrom<
                    ::openusd::sdf::Value,
                >>::try_from(
                        ::openusd::sdf::Value::Vec2f(::openusd::gf::vec2f(0f32, 0f32)),
                    )
                    .map(::std::option::Option::Some)
                    .map_err(::std::convert::Into::into)
            }
        }
    }
    /// Declared `float2 outputs:result`.
    pub fn result_output(&self) -> crate::shade::Output {
        <crate::shade::Shader as crate::shade::Connectable>::output(
            &self.0,
            tokens::RESULT,
        )
    }
}
