name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string
        default: '0.0.0'

      dryrun:
        description: 'Skip publish (--dry-run)'
        required: false
        type: boolean
        default: false

jobs:
  publish:
    name: 'Publish on crates.io'
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: write

    env:
      TAG: "v${{ inputs.version }}"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - run: cargo install cargo-edit
      - run: cargo set-version ${{ inputs.version }}

      - name: Setup Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"

      - name: Git commit & tag
        run: |
          git add Cargo.toml
          git commit -m "Bump crate version to ${{ inputs.version }}"
          git tag $TAG

      - run: cargo publish $SKIP
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATESIO_TOKEN }}
          SKIP: ${{ inputs.dryrun && '--dry-run' || '' }}

      - run: git push --atomic origin HEAD $TAG
