name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        type: string
        default: '0.0.0'

jobs:
  publish:
    name: 'Publish on crates.io'
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - run: cargo install cargo-edit
      - run: cargo set-version ${{ inputs.version }}

      - name: Setup Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Git commit & tag
        run: |
          git add Cargo.toml
          git commit -m "Bump crate version to v${{ inputs.version }}"
          git tag "v${{ inputs.version }}"

      - run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATESIO_TOKEN }}

      - run: git push --atomic --follow-tags
